### ISSUE TITLE
1.3.0 tag for alpine image

### ISSUE THREAD

**Issue by vijayendrabvs** [lyft/envoy#1035]
A 1.3.0 tag was cut for envoy but only for the ubuntu image on dockerhub. Can one be pushed for the alpine images as well? It'll help lock down stable releases in an identifiable format rather than use long/unreadable tags. Thanks!

**Comment by mattklein123** [comment]
Tag already exists here: https://hub.docker.com/r/lyft/envoy-alpine/tags/
