### ISSUE TITLE
isInternalAddress network utility function ipv6 support

### ISSUE THREAD

**Issue by hennna** [lyft/envoy#1044]
Should the network utility function isInternalAddress be upgraded to support IPv6 or is it stale code?

**Comment by mattklein123** [comment]
It is being used: https://github.com/lyft/envoy/blob/master/source/common/http/utility.cc#L136

And yes, definitely needs to be updated to support IPv6.

**Comment by hennna** [comment]
@mattklein123 Do you know what I need to #include for IP6T_SO_ORIGINAL_DST? That seems to be the IPv6 equivalent of SO_ORIGINAL_DST. I tried <linux/netfilter_ipv6/ip6_tables.h> but it doesn't come in cleanly.
