### ISSUE TITLE
replace IpList with CidrRange

### ISSUE THREAD

**Issue by hennna** [lyft/envoy#1045]
CidrRange seems to support both IPv4 and IPv6. Is the intention to replace IpList with CidrRange?

**Comment by mattklein123** [comment]
Yes, IIRC IpList is only used now in the client SSL auth filter (not sure where else). Anywhere we have a list of IP ranges and subnet masks, we should support both v4 and v6.

**Comment by jamessynge** [comment]
Yes, CidrRange was added expressly to support generalizing the support in
envoy for lists of IP addresses of either type.

**Comment by hennna** [comment]
Question about two input cases:

1. Currently, IpList does not allow the input IP address to set bits that are set in the mask. For example: 192.168.1.1/24 will throw. The current functionality of CidrRange allows this input behavior and will return a truncated address. For example 192.168.1.0 without error. Which is preferred?
2. Similarly, IpList doesn't allow mask lengths > 32 for Ipv4 addresses. CidrRange currently will return with the mask length = 32. Which is preferred?

**Comment by mattklein123** [comment]
@hennna re: (1) and (2) above, I don't have a strong opinion and would need to refresh my memory on the different call sites. Can you take a look at where things are used and make a proposal based on what makes the most sense? As long as the behavior is well documented I don't think it matters that much. (I would probably go with more permissive as long as the result is the same).

**Comment by hennna** [comment]
Seems to be instantiated in three places
1. TcpProxy source_ip
2. TcpProxy destination_ip
3. SSL ip_white_list
