### ISSUE TITLE
Add option to compile trace/debug messages on release builds

### ISSUE THREAD

**Issue by mattklein123** [lyft/envoy#1088]
We should add a define that allows compilation of trace/debug messages independent of NDEBUG. I'm undecided on whether this should be the default, but we should probably set it in CI for the release images that get pushed. I think this creates too much friction for new people that expect more logging.

@mrice32 not sure if you feel like covering this in the context of the other logging work you are doing.

**Comment by mattklein123** [comment]
Note to whoever does this, there are some places where logging is guarded via NDEBUG for multiple lines of code. Those cases need to be fixed also to look at the new define.

**Comment by mrice32** [comment]
Sure, this shouldn't be too bad.  I can add it to my current PR.

**Comment by mattklein123** [comment]
This is fixed.
