### ISSUE TITLE
proxy protcol follow up

### ISSUE THREAD

**Issue by hennna** [lyft/envoy#1095]
From #1032  
@hennna FWIW, I'm not a huge fan of this type of error checking of the C++ runtime functions by catching std exceptions. It can be really unclear what throws and why, and we might catch something that we don't intend. It's not a huge deal, but in this case, would rather see us just verify things using standard if length checks, and then using StringUtil::atoul which is a lot faster than the standard version. Not a big deal at all but we might consider a follow up. cc @htuch

**Comment by hennna** [comment]
@mattklein123 question on what you mean by "using standard if length checks"?

**Comment by mattklein123** [comment]
I just mean that for this code:

```
uint32_t remote_port, destination_port;
  try {
    remote_port = std::stoul(line_parts[4]);
    destination_port = std::stoul(line_parts[5]);
    // Check that TCP port value is in range [0, 65535].
    if (remote_port > 65535 || destination_port > 65535) {
      throw std::out_of_range("failed to read proxy protocol");
    }
  } catch (const std::invalid_argument& ia) {
    throw EnvoyException(ia.what());
  } catch (const std::out_of_range& ex) {
    throw EnvoyException(ex.what());
  }
```
I would check the cases that you think would/should cause an invalid_argument/out_of_range exception directly, and then let the process crash if some other invariant is not met. Basically, with this type of code and the way the std lib is written, you may be masking problems that you don't know you had.

**Comment by htuch** [comment]
Aren't the exceptions documented at http://en.cppreference.com/w/cpp/string/basic_string/stoul?

**Comment by mattklein123** [comment]
They are, but IMO it's very easy to accidentally mask behavior that "shouldn't happen" when catching the std exceptions (for example if line_parts has been accessed with at() which could also throw an exception if the logic was wrong above). This might not be the case here, and you can feel free to ignore, as it's really just a style preference. (However StringUtil::atoul will be faster as it doesn't attempt to process white space or minus). 

I don't feel that strongly about this, so feel free to close if you don't agree.

**Comment by hennna** [comment]
I'll close for now and revisit when we add more functionality to the proxy protocol code.
