### ISSUE TITLE
dns_impl_test fails when localhost does not resolve to ::1

### ISSUE THREAD

**Issue by rshriram** [lyft/envoy#1133]
I have Ubuntu 16.04 xenial (xubuntu). My /etc/hosts file looks as follows

```bash
127.0.0.1 localhost 
127.0.1.1 shriram-machine 
# The following lines are desirable for IPv6 capable hosts 
::1 ip6-localhost ip6-loopback 
fe00::0 ip6-localnet 
ff00::0 ip6-mcastprefix 
ff02::1 ip6-allnodes 
ff02::2 ip6-allrouters
```

Adding localhost to ::1 makes the test pass. Perhaps it might be worthwhile to check if ::1 resolves to ip6-localhost or ip6-loopback ?

Here is the error from dns_impl_test
```
test/common/network/dns_impl_test.cc:369: Failure
      Expected: nullptr
      Which is: NULL
To be equal to: resolver_->resolve("localhost", DnsLookupFamily::Auto, [&](std::list<Address::InstanceConstSharedPtr>&& results) -> void { address_list = results; })
      Which is: 0x15640c0
test/common/network/dns_impl_test.cc:371: Failure
```

I can confirm that ipv6 is not disabled in the kernel. and ifconfig shows valid(?) inet6 addr
```
lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:59267 errors:0 dropped:0 overruns:0 frame:0
          TX packets:59267 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:208935637 (208.9 MB)  TX bytes:208935637 (208.9 MB
```

@hennna ^^^

**Comment by hennna** [comment]
From discussion on gitter, my proposal is to require localhost v6 resolution and give a more descriptive error message when the dns_impl test fails here: https://github.com/lyft/envoy/blob/master/test/common/network/dns_impl_test.cc#L376

Ongoing issue is that the integration tests are probably failing silently when address_list returns empty here: https://github.com/lyft/envoy/blob/master/source/common/upstream/upstream_impl.cc#L453

**Comment by mattklein123** [comment]
fixed via https://github.com/lyft/envoy/pull/1135

**Comment by hennna** [comment]
Actually I think integration tests are not failing because we use fake upstreams.
