### ISSUE TITLE
What suggest to  deploy a 'service pod' on non-docker environment?

### ISSUE THREAD

**Issue by anticpp** [lyft/envoy#1146]
We deploy a 'service pod' with a service instance and the sidecar envoy, and other surrounding stuff.

ServicePod => |Service|Envoy |

It's very easy to deploy in k8s or other docker situation, though, not so easy in non-docker machine or vm. We have develop a tool to patch everything required in the service home directory. However,  It's to too weird, I think.

Any good solutions?

**Comment by mattklein123** [comment]
@anticpp this is a bit out of scope for what the Envoy project can provide. It really comes down to the specifics of your deployment (e.g., puppet vs. salt, how you do deploys, etc.). cc @louiscryan

**Comment by louiscryan** [comment]
Are you using anything for deployment / orchestration? Chef, Puppet etc ?

**Comment by anticpp** [comment]
No, we are not yet using any deployment. It will be in our future plan.

**Comment by anticpp** [comment]
The point is, we have implemented an initial version to our project, we don't want to introduce a 'heavy' deployment in our system at this moment. So, we are looking forward a relative 'light' solution.

**Comment by mattklein123** [comment]
Closing this for now as we have no plans to take on this type of ops work in the primary envoy project.
