### ISSUE TITLE
Add more granular timing information to RequestInfo

### ISSUE THREAD

**Issue by mrice32** [lyft/envoy#1179]
Envoy currently measures first byte received to last byte sent by taking a snapshot whenever the access log is called, which appears to happen whenever the stream is deleted.  It would be nice to measure and allow per-request logs to have access to total backend latency and, potentially, client RTT (this may be more difficult) for users to better understand latency bottlenecks.  It could also be beneficial to be more explicit about recording the latency when the stream is done encoding rather than when its destructor is called.  As far as I understand, the only way for a user to get these sorts of latencies now would be to do so in a filter.

**Comment by mrice32** [comment]
@dnoe

**Comment by mattklein123** [comment]
Backend latency is already available in https://lyft.github.io/envoy/docs/configuration/http_filters/router_filter.html#x-envoy-upstream-service-time header (and implicitly to access logs via response headers).

**Comment by mattklein123** [comment]
> It could also be beneficial to be more explicit about recording the latency when the stream is done encoding rather than when its destructor is called

This is the same thing right now because of the way end to end flow control (or lack there of) works. This will be fixable once @alyssawilk makes further progress on that front. We can then measure downstream latency correctly in terms of when all  buffered bytes are flushed (at least up to TCP level).

**Comment by dnoe** [comment]
The X-Envoy-Upstream-Service-Time is what I am using to fill out the upstream_service_duration field of the AccessLog proto.

**Comment by mrice32** [comment]
I see. That all makes sense. Thanks. I wasn't aware of the various aggregate statistics that the router keeps and outputs. 

> We can then measure downstream latency correctly in terms of when all buffered bytes are flushed (at least up to TCP level).

I was referring to the deferred delete of streams (potentially) throwing off when the access logs are called, but I wasn't aware we had plans to report it to this level of accuracy. Okay, I'll wait for progress there. 

Thanks for the references.  I'll close for now, and reopen if there are any latencies that aren't available through the router filter.
