### ISSUE TITLE
xDS API connection affinity

### ISSUE THREAD

**Issue by htuch** [lyft/envoy#1195]
While canarying a set of logically related xDS APIs, it's helpful if Envoy speaks to only a single management server.

To achieve this, we could modify `Grpc::AsyncClient` to ensure that it always reuses a connection to a specific cluster and have all the xDS APIs configured to speak to the same cluster. Maybe this is how `httpAsyncClientForCluster` works effectively today, but should verify.

@mattklein123 Can you comment on Lyft's canary requirements wrt the above?

@tschroed @dnoe

**Comment by mattklein123** [comment]
AsyncClient under the hood uses the full router/connection pool, etc. so you will get standard keep alive semantics.

I'm a little confused though what specific behavior you are looking for. In whatever detail is possible can you describe your management server topology and how you are hoping canary to work?

**Comment by htuch** [comment]
Consider a setup in which you have management servers X, Y, Z. Via some mechanism, Y is selected to perform canary on an Envoy instance. Y is responsible for pushing out the configs and monitoring the Envoy instance for its ACK/NACK of the various configs. We're trying to avoid having X, Y and Z coordinate on the different config ACK/NACKs across the APIs. 

There's also an issue beyond canary to consider. We would like to ensure that config pushes don't blackhole traffic at any point. So, if we want to update both LDS/RDS, we want to push RDS first (for some new route table name), wait for ACK and then LDS. This is easier to do if we can have a single management server involved.

**Comment by mattklein123** [comment]
OK I see. @ccaraman and @junr03 can comment more as they are bringing up our xDS management server now, but our general plan for canary was to have the management server deal with it as we effectively announce canary via the Node concept (we are doing v1 now but it works the same way with REST URL slugs). So the management server would serve canary data to canary envoys. (This is orthogonal to canarying the management server itself).

For us, we haven't been worrying about eventual consistency and a small batch of 404s, etc. is OK in our environment.

I hadn't considered the case where we want all the APIs to go to the same physical server if possible. Just brainstorming I think we could do the following:
- Switch from inline cluster definitions in the CDS/SDS to reference semantics. (Basically like RDS/LDS the cluster needs to be defined and is referred to by name). This would be a simple change and then would allow CDS/SDS/etc. to talk to the same cluster if desired.
- We might consider a new LB type, "RandomPrefersExistingConnections" or something like that. In this LB type, the load balancer will pick a host with an existing connection if possible.
- If you want canary envoy to target canary management server only, this will be possible with the LB hint mechanism also.

i will think on it more but this would be my quick first proposal.

**Comment by htuch** [comment]
Yeah, existing LB affinity mechanisms don't cover this scenario. We're essentially talking about a cluster with precisely one connection upstream at a time. The mechanism could be generalized by maintaining multiple connections and using a header or something to force affinity to one of them, but there's probably no demand for this.

**Comment by mattklein123** [comment]
@htuch @tschroed now that I think we have agreed to build "ADS" per https://github.com/lyft/envoy-api/issues/102 can we close this?

**Comment by htuch** [comment]
Agreed, https://github.com/lyft/envoy-api/issues/102 deprecates this, closing.
