### ISSUE TITLE
Provide ability to change service cluster post start

### ISSUE THREAD

**Issue by rshriram** [lyft/envoy#1229]
In kubernetes pods are late bound to services (i.e. pods created first and then attached to service objects). So when running Envoy as sidecar in a pod, it's not possible to pre determine the service name associated with the pod for a certain period of time. 

Our current solution is to start the sidecars with a generic service name (istio-proxy) but that brings its own set of complexities (e.g. zipkin traces have no service names).

It would be nice to be able to change the service cluster associated with the pod at runtime without hot restarts. One solution that comes to my mind is to add an API to the admin server to do this. Thoughts ?

**Comment by mattklein123** [comment]
All of the node information is pulled out of `LocalInfo` currently. (Though it's possible there are some legacy places that read from `LocalInfo` once and never check again. This needs to be audited). Although there are some threading issues to sort out, theoretically it should be OK to change the contents of `LocalInfo` at runtime.

With that said, this brings up semantic complexities, as when Envoy boots, it starts fetching things from xDS using the node info. 

IMO it would be better to think deeply about whether this is really required. (I.e., is it possible to not start Envoy until the service info is known).

**Comment by dnoe** [comment]
> IMO it would be better to think deeply about whether this is really required. (I.e., is it possible to not start Envoy until the service info is known).

This is the approach we are taking (binary starts, then waits for the opaque node identity info, then calls the Envoy common main to start Envoy with that info).

**Comment by mattklein123** [comment]
Per https://github.com/lyft/envoy-api/issues/98 closing this out for now as won't fix.
