### ISSUE TITLE
Missing reference link in docs?

### ISSUE THREAD

**Issue by ihac** [lyft/envoy#1239]
Hi,
    I was assigned to get familiar with the src code of Envoy. I started with docs in both Github and the [official website](https://lyft.github.io/envoy/docs/).
    It confused me that Github docs always used sth like **:ref: \`cluster <config_cluster_manager_cluster>\`** to refer another doc in (perhaps?) Envoy website. Is this something trivial remaining to be fixed yet? or did I get it wrong?

XIAO An

**Comment by jwfang** [comment]
i guess that's *reStructuredText* links. 
i am curious why do you need to read the raw *reStructuredText*; for docs, you can just read the generated html online.

**Comment by mattklein123** [comment]
Per @jwfang you are trying to read raw RST through GH which doesn't work. Please look at the docs here: https://lyft.github.io/envoy/docs/index.html

If you need to edit the docs I have found that the atom editor works well.
