### ISSUE TITLE
XFCC header parsing subtly broken

### ISSUE THREAD

**Issue by timperrett** [lyft/envoy#1252]
@myidpt @PiotrSikora The mTLS certificate is not having its fields correctly extracted from the inbound certificate. 

**Exhibited Behavior**

When adding:

```
\"XFCC %REQ(X-FORWARDED-CLIENT-CERT)%\” 
``` 
to the access log, one only sees the following result:

```
XFCC "Hash=e432f466298ea55e65fc979a1e3f7774ee1f93ba4ef267b0767d1ff652d61a15”
```

**Expected Behavior**

Assuming the same logging line as above, i'd expect to see the `Subject`. This particular certificate does not have a SAN, so the `By`

```
XFCC "Subject="CN=laptop.local";Hash=e432f466298ea55e65fc979a1e3f7774ee1f93ba4ef267b0767d1ff652d61a15”
```

Here's an `openssl x509` for one of my local testing certificates:

```
λ openssl x509 -in cert.pem -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            QQQQQQQQQQQQQQQQQQQQQQ
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, ST=CA, L=San Jose, O=XXXX, OU=YYYY, CN=ZZZZ
        Validity
            Not Before: Jul 12 22:42:46 2017 GMT
            Not After : Jul 12 22:43:16 2018 GMT
        Subject: CN=laptop.local
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
            RSA Public Key: (2048 bit)
                Modulus (2048 bit):
                    ...
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment, Key Agreement
            X509v3 Extended Key Usage:
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Subject Key Identifier:
                46:C7:F3:35:B0:86:9E:B9:AF:86:9A:A5:8B:19:9D:0E:6C:BC:F7:05
    Signature Algorithm: sha256WithRSAEncryption
        ...
```

**Comment by timperrett** [comment]
For anyone else who struggles with this same issue, the problem is that you need a config block something like:

```
            "forward_client_cert": "append_forward",
            "set_current_client_cert_details": [
              "Subject"
            ],
```

Unfortunately the interplay of `set_current_client_cert_details` and `forward_client_cert` was not entirely obvious to me until reading the source code for the parser.

**Comment by mattklein123** [comment]
@timperrett doc PR would be appreciated for making this more clear.

**Comment by timperrett** [comment]
@mattklein123 absolutely - i'm going to put one together today. Just lost like an hour on this :-D

**Comment by myidpt** [comment]
Thank you @timperrett. I appreciate it.

Sorry guys for the troubles. The design of using two fields is not very straight-forward, it would be great if we can make the doc better written.
