### ISSUE TITLE
wierd "pure virtual method called" fault

### ISSUE THREAD

**Issue by jwfang** [lyft/envoy#1254]
envoy version:
> ./envoy-debug-no-signal-trace --version
> ./envoy-debug-no-signal-trace  version: f98f5d9f8eac4a4bc4fb40112a5a5248e44226c0/Clean/DEBUG

we are run envoy by docker-compose, and local service are discoveried via *strict_dns*.
we start envoy before local services, so the DNS may fail for the first time.
PS: we also tried start envoy last, and this seems not reproduce the problem yet.

below are the config/log/gdb, they are from my self built envoy on centos, with *signal_trace=disabled*
we also tried using the official **lyft/envoy** image, the problem also could easily reproduced.

envoy config: https://gist.github.com/jwfang/cbc9722e305ab8d17d17f030777cd1c6
trace log snippet: https://gist.github.com/jwfang/ec44acedbaf9358ef498828cdbfa018a
gdb session: https://gist.github.com/jwfang/80940e996769d9f05afd51cddd3ff38e

**Comment by mattklein123** [comment]
@jwfang I think this is an interaction between "local_cluster_name" and CDS clusters. I strongly suspect it has nothing to do with the xxx cluster. I'm pretty sure there is a pretty bad bug related to local cluster updates and potentially a cluster that has been deleted. Do you know if CDS has initialized at this point and added/removed hosts? It's hard to tell what is going on here without full logs, etc.

**Comment by jwfang** [comment]
CDS is an external service outside this *docker-compose*.
there are other local services, but only *xxx* service is both local and available via CDS/SDS. and when envoy fault, the stack trace and trace log are similar: dns success for *xxx*, update hosts, fire callbacks, BOOM ...

i will try simplified the environment and provides more informations tomorrow.

**Comment by mattklein123** [comment]
OK. Sorry, it's hard to tell with the info provided. If you can't narrow it down more/debug, please provide the full config, full debug logs from startup to crash, and optimally, the core dump with associated binary with symbols.

**Comment by jwfang** [comment]
@mattklein123 
i simplified the fault, it's [here ](https://github.com/jwfang/envoy-pvmc.git).
the README there brifely explain how to reproduce.

**Comment by mattklein123** [comment]
Thanks @jwfang I will look today.

**Comment by mattklein123** [comment]
@jwfang I know what the problem is but unfortunately there are two different problems and it's going to take a little bit of time to fix. 

In the meantime I would just remove "local_cluster_name" from your config and you should be ok. (I assume you are using this because you want zone aware routing?).

**Comment by jwfang** [comment]
@mattklein123 
thanks for your quick response. i will rerun the test once it's done.
there are no problem for the fix time. we are still in the early stage, and have work around for this.

BTW: could you briefly explain what's casuing this fault, or point me to the related PR ? just curious, and from my quick galance of the code i saw no clue. :(

**Comment by jwfang** [comment]
@mattklein123 thanks for your pointer. you're really quick.

i totally missed the fact that *local_host_set_* has different life-cycle with *host_set_*.

after read your PR, there is still one thing not clear for me:
why all *LoadBalancer* need to be notified for *local_host_set_* changes ?
i guess maybe we only need to notify the *LoadBalancer* which has the same name as *local_cluster_name* ?

**Comment by mattklein123** [comment]
> why all LoadBalancer need to be notified for local_host_set_ changes ?

This only happens when you set "local_cluster_name" which is only useful when doing zone aware load balancing. The load balancer uses information about the "local cluster" to correctly balance traffic across all zones. Thus, all load balancers need to know about the local cluster. If you are not doing zone aware balancing via SDS, I would just not set "local_cluster_name" at all. It's not necessary.
