### ISSUE TITLE
Dynamic config canary dry run

### ISSUE THREAD

**Issue by htuch** [lyft/envoy#1260]
In the v2 API, we've added a `canary` field (https://github.com/lyft/envoy-api/blob/ea695fb3012b574e78a8b2f396664ee5253da4de/api/base.proto#L135) to `DiscoveryResponse`.

The intended semantics when `--dry-run-canary` is supplied on the Envoy command line is that canary configs are never applied, only validated. Validation should include at least schema/constraint checking, as well as catching any `EnvoyException` during `onConfigUpdate` and using this for ACK/NACK purposes.

**Comment by htuch** [comment]
@rohitbhoj

**Comment by htuch** [comment]
@mattklein123 Can you comments on how LDS and the bind/listen story would interact with dry run? Are there any failure scenarios we would pick up in actually applying when it comes to port listening that would be missed in a dry run?

**Comment by mattklein123** [comment]
The only one I can think of is the one I just referenced in https://github.com/lyft/envoy/pull/1257 which would be a failure to listen() even though we were able to bind(). IMO this is enough of an edge case that I think we can ignore this.

I still think that we will need a more complete design of what dry run means across all of the different APIs. It can potentially get quite complicated.

**Comment by htuch** [comment]
I think for CDS/EDS at least (where I've been spending some time recently, so I'm familiar), it's not that hard to be concrete about what happens in dry runs. For EDS today, it's anything in https://github.com/lyft/envoy/blob/master/source/common/upstream/eds.cc#L37 that would raise an `EnvoyException`. For CDS, its this in https://github.com/lyft/envoy/blob/master/source/common/upstream/cds_api_impl.cc#L49. 

I haven't fully audited the causes, but they seem to be mostly around config schema validation failures and things which are morally equivalent, e.g. https://github.com/lyft/envoy/blob/master/source/common/upstream/logical_dns_cluster.cc#L25. For LDS, there's also things like ensuring you have the right filters for the filter chain around, ports can be bound to, etc. Again, it's anything that would cause an `EnvoyException` in https://github.com/lyft/envoy/blob/128200786aa4770cb8b1964240463168636d2c59/source/server/lds_api.cc#L35.

If we want dry run semantics, we're going to have to plumb and condition on a dry run variable in the full call graph rooted at `onConfigUpdate()`  (nee `parseResponse()`) for each API. Where it gets trickier in LDS is you would need to bind/unbind to do the validation in https://github.com/lyft/envoy/blob/128200786aa4770cb8b1964240463168636d2c59/source/common/network/listen_socket_impl.cc#L23 without leaving any state around.

After thinking about it, I agree that my above question is probably not relevant to dry run - the actual listen happens much later.

This is starting to look more complex than I had originally envisioned. With the above in mind, I'm going to circle back to some internal folks and check with them if we can envisage pushing some of this to the management server by having it push a config and then roll it back.

**Comment by htuch** [comment]
Actually, the more I look at this, the more complex it looks. See https://github.com/lyft/envoy/blob/master/source/common/upstream/cluster_manager_impl.cc#L263 for example, there's a lot of state that gets committed that is then relied upon later. Even if the existence of the state doesn't matter to the initialization (which it does almost certainly in some places), the fact that we would then need to restructure these entire tree of control flow into distinct validation and commit phases seems a big restructuring.

@mattklein123 Would this be your assessment as well?

**Comment by mattklein123** [comment]
Yes, I think this will be extremely complicated. (Think what @rlazarus was doing with the config verification but worse). I would really recommend just doing standard rollout/rollback procedures.

**Comment by htuch** [comment]
After some offline discussion, we arrived at the following two design alternatives, both of which involved batching up API refreshes via ADS in order to provide a complete configuration set (weaker per API canarying is still possible without ADS).

1. Weak configuration constraint checking. Essentially the moral equivalent of the JSON schema checks today. This can be easily provided with some small changes to the xDS implementations today.

2. Perform a deep copy of all listener/cluster manager, relevant filter state etc. Apply a mutating config update during dry run to the copy. Check to see if any `EnvoyException` is thrown during the process. Envoy would take a batch of xDS updates via ADS and execute them in order, only ACKing once all are applied successfully. This provides high confidence that when this same sequence is delivered in a real update, they would all commit successfully. The main work here is to add the clone support across a large swathe of Envoy interfaces/implementations.

**Comment by htuch** [comment]
We no longer require this, so closing out for now. If someone would like it later, we can reopen.
