### ISSUE TITLE
LDS without LDS Cluster definition crashes Envoy on startup

### ISSUE THREAD

**Issue by stolsma** [lyft/envoy#1264]
Hello,

Just started to test the latest version with LDS implemented and found out that Envoy crashes at start-up (exit code 134, and core dump) when LDS and CDS are defined (without the referenced LDS cluster defined) and CDS didn't return the LDS cluster definition but just an empty cluster list or even an 404 response.

What we are trying to accomplish is a sort of  auto discovery of Envoy gateways by using the first CDS call to signal the presence of a new envoy gateway in our company wide discovery server. An operator then 'defines' the configuration of the new gateway (CDS, LDS, SDS and RDS data) and we thought that one of the next requests of CDS (could be after hours of empty CDS reply or 404's) would then kick-start the new gateway with the correct dynamic config (including the LDS endpoint location) via CDS, LDS, SDS, RDS...

Is the crash a bug or normal behaviour and is it always required to have a valid LDS cluster defined in the cluster configuration (static or in de first CDS reply)??

Thanks btw for open sourcing  the code!!!

Sander

**Comment by mattklein123** [comment]
Currently the LDS cluster must be a static cluster at startup. It can't be delivered via CDS. It's a bug that the configuration does not fail to load. I will fix today. Thanks for reporting.

**Comment by stolsma** [comment]
Thanks for the quick reply! We will then change our 'new gateway' discovery adding process by configuring the LDS cluster description in the initial cluster config...

Are there any plans to let a starting envoy instance discover its initial configuration from a central mgmt node (Location given by cmd line option...)?

**Comment by mattklein123** [comment]
> Are there any plans to let a starting envoy instance discover its initial configuration from a central mgmt node (Location given by cmd line option...)?

Not currently. If you are using all the xDS APIs, the bootstrap config is pretty much static and probably < 50 lines. With that said, adding a `--config-from-url` option would not be hard and seems like a good idea. Feel free to open a GH issue on that.
