### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by skyrocknroll** [lyft/envoy#1271]
envoy  version: 4d43aa36b6496a300d3b48502cd239795a7df27b/Clean/RELEASE
container image : ubuntu 16.04 
stdout.log 
http://paste.ubuntu.com/25110053/
stderr.log
http://paste.ubuntu.com/25110052/

We use supervisor to start the process using hot restarter. Also we use consul-template to render the envoy.json.

**Comment by mattklein123** [comment]
At minimum please provide a decoded backtrace using gdb. Optimally, please provide a core dump with matching symbols.

**Comment by skyrocknroll** [comment]
@mattklein123 Sorry. I am completely new to c++ and c code base. I will figure out and come back with details.

**Comment by mattklein123** [comment]
If you need help with commands to get core dumps / use gdb feel free to hop in gitter and someone can help out.

**Comment by mattklein123** [comment]
Going to close this for now. Please reopen when you have more info. Would love to get this fixed.
