### ISSUE TITLE
Http::Utility::sendLocalReply() does not respect stream reset

### ISSUE THREAD

**Issue by htuch** [lyft/envoy#1283]
This static helper function doesn't take into account that the caller (e.g. router) might have had its stream reset between `encodeHeaders()` and `encodeData()`. This is worked around in https://github.com/lyft/envoy/pull/1282 for router replies in the context of `Http::AsyncClientImpl`, but probably deserves a more complete solution.

**Comment by htuch** [comment]
It looks like the only call sites for `Utility::sendLocalReply()` are in `source/common/router/router.cc`. I think we could either:
1. Swallow this static into `Router::Filter`, where it can get at instance variables to figure out if the request has been reset.
2. Split into `Utility::sendLocalReplyHeaders()` and `Utility::sendLocalReplyData()` with the sender responsibility to check stream validity in between.

There are other more involved ways to fix (e.g. passing in a validity callback etc.), but I think since the use is so localized, either of the above should work well. @mattklein123 WDYT?

**Comment by htuch** [comment]
I stand corrected, ti's used in `source/common/grpc/json_transcoder_filter.cc` as well.

**Comment by mattklein123** [comment]
I think (2) is probably OK given the small # of call sites. As discussed offline, I think we could also pass a `const bool& is_reset` parameter and make the caller manage it. This is a bit simpler than the lambda as callers are probably managing a boolean anyway, but admit it's a bit strange. I could go for any solution.

**Comment by mattklein123** [comment]
@htuch this code https://github.com/lyft/envoy/blob/master/source/common/http/filter/buffer_filter.cc#L41 should probably use sendLocalReply (this is going to become more important when we allow overriding error response messages). No need to fix it in this PR, but can you drop a TODO in? There may be other sites liker this I can't remember.

**Comment by mattklein123** [comment]
Fixed by https://github.com/lyft/envoy/pull/1282
