### ISSUE TITLE
gperftools doesn't seem to be detecting leaks

### ISSUE THREAD

**Issue by mrice32** [lyft/envoy#1306]
tcmalloc (and the dependent gperftools) seems to be only be linked in [non-asan builds](https://github.com/lyft/envoy/blob/4f9d60d8b07fe9e306682223a8bea4d8397725ea/tools/bazel.rc#L24).  As far as I'm aware, when tcmalloc is linked, it should allow gperftools to detect leaks through a heap checker.  However, in the process of tracking down some internal leaks, I introduced the following sample leak into [router.h](https://github.com/lyft/envoy/blob/4f9d60d8b07fe9e306682223a8bea4d8397725ea/source/common/router/router.h#L111):
 
```
Filter(FilterConfig& config)
      : config_(config), downstream_response_started_(false), downstream_end_stream_(false),
        do_shadowing_(false) {
          int *leak = new int;
          std::cout << "leak address: " << leak << ", leak data: " << *leak << std::endl;
          leak = new int;
          std::cout << "leak address: " << leak << ", leak data: " << *leak << std::endl;
        }
```
This leak is only detected by the `bazel.asan` docker command by the asan LeakSanitizer.  Other docker builds/tests (`bazel.dev`, `bazel.debug`, `bazel.release`, `bazel.tsan`) pass.  If this is the expected behavior, that's fine.  It just seemed surprising that gperftools either wasn't enabled or detecting this unambiguous leak on any of the docker commands where one might expect it to.

**Comment by mattklein123** [comment]
Heap checking should be enabled in normal builds via https://github.com/lyft/envoy/blob/master/ci/build_setup.sh#L7. I can check this locally in a sec. If that's not working correctly I think something broke somewhere along the way.

**Comment by mattklein123** [comment]
@mrice32 yeah I think something is broke. I'm not seeing normal heap check output when I run tests via bazel even w/ env var set. I can investigate in a bit, trying to fix something else. cc @htuch in case he knows what might be broke.

**Comment by mrice32** [comment]
Okay, I'll do some poking around to see if I can find the source of the problem.

**Comment by htuch** [comment]
i'm guessing it's some link issue (mattrice@ suggested it might be link order). Probably happened in the Bazelification.
