### ISSUE TITLE
watchdog config missing from TOP_LEVEL_CONFIG_SCHEMA

### ISSUE THREAD

**Issue by bplotnick** [lyft/envoy#1352]
The config [docs](https://lyft.github.io/envoy/docs/configuration/overview/overview.html) mention watchdog configuration options, but they are not listed in the json [schema](https://github.com/lyft/envoy/blob/master/source/common/json/config_schemas.cc#L1092), so adding these configurations causes config schema validation failure.

The relevant options are:
```
watchdog_miss_timeout_ms
watchdog_megamiss_timeout_ms
watchdog_kill_timeout_ms
watchdog_multikill_timeout_ms
```

It's friday night for me, so i'm opening a ticket instead of a PR, but if nobody gets around to this, i'll go ahead and fix it.

**Comment by mattklein123** [comment]
cc @dnoe
