### ISSUE TITLE
Unable to get external IP address behind AWS ELB

### ISSUE THREAD

**Issue by fabware** [lyft/envoy#136]
As I know AWS ELB doesn't support HTTP2 now, so I have to use it's TCP mode route traffic to an envoy instance. In this case envoy will populate X-Fowarded-For with inner IP address seems belong to ELB itself, and X-Envoy-External-Address is empty.

Is there any solution to this problem?

PS, log format as below:

"format": "[%START_TIME%] \"%REQ(:METHOD)%\" \"%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%\" %PROTOCOL% %RESPONSE_CODE% %FAILURE_REASON% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% \"%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%\" \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(X-ENVOY-EXTERNAL-ADDRESS)%\" \"%REQ(appid)%/%REQ(appversion)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\"\n"

**Comment by mattklein123** [comment]
You need to use the proxy proto support in the ELB:
"use_proxy_proto" https://lyft.github.io/envoy/docs/configuration/listeners/listeners.html

http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-proxy-protocol.html

**Comment by fabware** [comment]
My bad, grab docs too quickly. Problem solved, really helpful. 

Thank you.
