### ISSUE TITLE
Invalid target on build

### ISSUE THREAD

**Issue by rakyll** [lyft/envoy#1376]
Instructions on https://github.com/lyft/envoy/tree/master/bazel suggests the following for the fastbuild target.

```
./ci/run_envoy_docker.sh ./ci/do_ci.sh bazel.fastbuild
```
```
$ ./ci/run_envoy_docker.sh "./ci/do_ci.sh bazel.fastbuild"
M	WORKSPACE
M	bazel/get_workspace_status
M	tools/bazel.rc
HEAD is now at 8442ed7... Improve CI testing. (#13)
building using 1 CPUs
Invalid do_ci.sh target, see ci/README.md for valid targets.
```

The command fails with `Invalid do_ci.sh target`.

**Comment by mattklein123** [comment]
Sorry docs are out of date. See here: https://github.com/lyft/envoy/tree/master/ci#building-and-running-tests-as-a-developer

Feel free to do PR to fix the docs or we can get to it in a bit.
