### ISSUE TITLE
SDS with service https protocol availability 

### ISSUE THREAD

**Issue by syukur91** [lyft/envoy#1405]
So, I created SDS Api to get services dynamically. One of the service object is like below

```{
    "hosts": [
        {
            "ip_address": "10.0.17.4",
            "last_check_in": "22-08-2017",
            "port": 4444,
            "revision": "1",
            "service": "hydra_service",
            "service_repo_name": "node1",
            "tags": {}
        }
    ],
    "env": "production",
    "service": "hydra_service"
}
```

in the documentation ```https://lyft.github.io/envoy/docs/configuration/cluster_manager/sds_api.html#config-cluster-manager-sds-api``` it tells that you should provide hosts array and the structure like below 
```{
  "ip_address": "...",
  "port": "...",
  "tags": {
    "az": "...",
    "canary": "...",
    "load_balancing_weight": "..."
  }
}
```
I run my service above using docker container, the access should be via https protocol. Is there any other configuration that can be https protocol enabled? or can you provide it? 

Thank's in advance

**Comment by mattklein123** [comment]
I'm not totally sure what behavior you are asking for. What access do you want to be via HTTPS?

**Comment by syukur91** [comment]
the host access, so the point is in each host configuration you can have an option to access whether via http or https,  if I imagine it, you'll have a configuration like below

```
"hosts": [
        {
            "ip_address": "10.0.17.4",
            "protocol": "https" <-- https protocol option
            "last_check_in": "22-08-2017",
            "port": 4444,
            "revision": "1",
            "service": "hydra_service",
            "service_repo_name": "node1",
            "tags": {}
        }
    ]
```

**Comment by mattklein123** [comment]
Currently, Envoy assumes that all hosts in a cluster are the same. The way that you would handle this is to have a TLS cluster and a non-TLS cluster and route appropriately.

**Comment by mattklein123** [comment]
Closing as question has been answered. Feel free to reopen if there are additional questions.
