### ISSUE TITLE
Support binding to a specific address when connecting to upstream servers

### ISSUE THREAD

**Issue by tschroed** [lyft/envoy#1411]
Like the title says. We should be able to specify an address for Envoy to bind to when connecting to upstream servers.

@htuch

**Comment by htuch** [comment]
So, we need to `bind` to a an address that we need to allow to be specified optionally in the `Cluster` definition before `connect`. @tschroed do we need this to come from CDS or some local option like a command-line flag (which could be simulated in a site-local binary via custom `Options`)?

**Comment by dnoe** [comment]
I think the best would be something that is resolved via a custom resolver we run in our "half" of the binary.

**Comment by dnoe** [comment]
Actually, getting ahead of myself a bit: The custom resolver is the best way to resolve LDS and EDS addresses to what we need. The source address could come from a "command line flag" that we simulate via custom Options, or from resolving a special address with the custom resolver we already need for resolving LDS and EDS addresses. This is also the case where we need IP_FREEBIND.

**Comment by htuch** [comment]
OK, so for this issue, it should probably be sourced on the CLI. I think we could do this by making it part of the bootstrap proto, since I have a feeling we're going to want to provide other parts of this proto on the CLI, so we can just feed it in as a string there.

**Comment by dnoe** [comment]
Bootstrap proto sounds perfect for this.

**Comment by htuch** [comment]
Great. The only downside to bootstrap proto is it doesn't allow specialization per-cluster, it would be a global setting. It's fine for us, but we might want to further down the track add some indirection table there to allow cluster to point at a specific outbound IP handle entry. Just thinking aloud, we have a solution for today.

**Comment by alyssawilk** [comment]
Conveniently, that issue is addressed by us needing per-cluster overrides anyway :-)
