### ISSUE TITLE
perf/debugging scripts

### ISSUE THREAD

**Issue by mattklein123** [lyft/envoy#1415]
We should have some scripts that automate:

- Taking a profile via perf and generating a flame graph for sharing
- Dumping /clusters, /stats, etc.
- Capturing launch config.

This will make it much easier for issue reporting/investigation.

**Comment by htuch** [comment]
I'll take this as a weekend project. I'll try and get a two-for and support capturing traces for debugging when doing non-perf work with the same wrapper.
