### ISSUE TITLE
Envoy should add a Binary Annotation to the Zipkin Span that contains the request target service

### ISSUE THREAD

**Issue by clguimanMSFT** [lyft/envoy#1419]
Let's assume the following scenario:
**service-a** sends a request to **service-b**. Envoy is configured to resolve **service-b** to either s**ervice-b-1** or **service-b-2** using a weighted cluster configuration.

The Zipkin Span sent from **service-a**'s envoy doesn't contain any information on the exact cluster to which the request was sent; The only thing that can be used is the **host_header** binary annotation which will just say "service-b", because the header was set by service-a and not the envoy. 

My proposal is to add a new binary annotation, **upstream-service-cluster**, that will contain the cluster name of the service that will receive the request.

What do you think?

**Comment by mattklein123** [comment]
> There's also the very confusing header x-envoy-downstream-service-cluster which actually contains the upstream cluster name and not the downstream (in this example it will be "service-a-1" or whatever the service-a's envoy was configured to

This is meant to be used by the upstream host, so it's kind of unrelated to what you are asking about.

> My proposal is to add a new binary annotation, target-cluster, that will contain the cluster name of the service that will receive the request.

This sounds reasonable to me. I would just do this in the driver agnostic code so it applies to all drivers.
