### ISSUE TITLE
grpc_json_transcoder broken in :latest docker container

### ISSUE THREAD

**Issue by Sergio-Slobodrian** [lyft/envoy#1427]
Hi,

Firstly good job with the grpc_json_transcoder it really simplifies things the architecture for my application. As of yesterday it appears that the grpc_json_transcoder functionality has been broken. I pulled a previous container at commit hash 092f01381467dfc3324e5e9528c67ee5d65744fd and that one is working correctly so presumably a commit following that one broke it.

Thanks in advance.
Sergio

**Comment by htuch** [comment]
How is it broken @Sergio-Slobodrian? Can you share logs/stats etc? Currently looking at #1406, wondering if there is something related.

**Comment by Sergio-Slobodrian** [comment]
Hi, Just some more information on what the symptoms of the issue are:
The access log shows that the HTTP/1.1 URL is correctly translated to the HTTP2 URL but it always returns a 404 (not found) despite the fact that the HTTP2 URL is correct. In the working version the exact same entry is shown in the log but with a return code of 200. Hopefully this helps get to the bottom of the issue.

**Comment by mattklein123** [comment]
Can you provide full config, and output of /stats and /clusters from admin? @lizan do you mind taking a look at this also? I agree with @htuch it's possible it's somehow related to the other issue.

**Comment by mattklein123** [comment]
@rshriram @lizan I think this is a regression from the WebSocket change (https://github.com/lyft/envoy/pull/1274). 

Basically, before this change, we would typically load the cached route for the first time in the router filter in a typical transcoding/router setup. Now we load it before we actually run any filter code at all: https://github.com/lyft/envoy/blob/master/source/common/http/conn_manager_impl.cc#L491

The transcoding filter modifies path, which depending on how the route table is setup would not match the original route.

I think we need to add a method that filters can call to refresh/clear the cached route entry so that subsequent filters will pick up the right one.

I'm not sure if this is the same issue or not as #1406. (I'm a little suspicious that it is the same issue but it might be).

**Comment by Sergio-Slobodrian** [comment]
Hi,

I need to roll back my environment to use the failing version so it’s going to take a little while. I should get it done before the end of the day est.

Cheers…

Sergio

**Comment by lizan** [comment]
sure I will take a look later today.

**Comment by Sergio-Slobodrian** [comment]
Hi,

Attached is the full config that I’m using as well as the output from /clusters and /stats from admin and the access log from the failing listener. The http2 listener doesn’t have any issues.  I’ll leave the broken environment set up for a little bit longer in case you need additional information.

Cheers…

Sergio

**Comment by mattklein123** [comment]
@Sergio-Slobodrian can you put them into the issue or supply gist links?

**Comment by Sergio-Slobodrian** [comment]
Sure… I’ll do that right now.

**Comment by Sergio-Slobodrian** [comment]
As requested:

[voltha-grpc-proxy.json.txt](https://github.com/lyft/envoy/files/1216022/voltha-grpc-proxy.json.txt)
[admin.clusters.txt](https://github.com/lyft/envoy/files/1216023/admin.clusters.txt)
[admin.stats.txt](https://github.com/lyft/envoy/files/1216024/admin.stats.txt)
[voltha_access1_log.log.txt](https://github.com/lyft/envoy/files/1216026/voltha_access1_log.log.txt)

Cheers...

Sergio

**Comment by mattklein123** [comment]
@Sergio-Slobodrian are you sure the stats dump matches? I don't see any 404s.

Either way with access log this does look similar to the other issue, but given the route tables, I'm very skeptical that the caching issue is really the issue. @lizan @rshriram @htuch

**Comment by Sergio-Slobodrian** [comment]
Yes,

The stats dump matches I ran all the requests on a brand new deployment using the latest docker container and this is what I’m getting. I ran a script to issue the curl commands and then I collected all the info. In the stats I see:

http.ingress_http1.no_route: 106

Which is consistent with the number of 404s I got.

Cheers…

Sergio

**Comment by Sergio-Slobodrian** [comment]
Would it help if I re-ran this on a working version and provided the access log and stats files?

**Comment by mattklein123** [comment]
Nevermind I see it. Sorry.

How easy is it for you to run different containers? Can you potentially bisect when the problem started? I'm mostly curious if it works right before https://github.com/lyft/envoy/commit/8c42f16163c7b36df75f503d669d7171d0961571 but fails with that commit.

There is definitely an issue here per linked issue, but it's not clear to me that it would effect your configuration.

**Comment by Sergio-Slobodrian** [comment]
I've set myself up to make is easy to swap out the container... it's a simple change to a Dockerfile, rebuild, and and re-deploy. I'll go pull the commit before 8c42f16163c7b36df75f503d669d7171d0961571 and try it out.

**Comment by mattklein123** [comment]
Thank you @Sergio-Slobodrian !

**Comment by Sergio-Slobodrian** [comment]
I just tried it at commit 29361deae91575a1d46c7a21e913f19e75622ebe which is the one immediately preceeding 8c42f16163c7b36df75f503d669d7171d0961571 and it works fine.

**Comment by Sergio-Slobodrian** [comment]
I just tried at commit 8c42f16163c7b36df75f503d669d7171d0961571 and that's exactly where it breaks.

**Comment by mattklein123** [comment]
Thanks you @Sergio-Slobodrian ! We are on it.

**Comment by mattklein123** [comment]
This is https://github.com/lyft/envoy/issues/1434. Closing this for now. Please watch that issue for fix. Thank for reporting and helping to debug!
