### ISSUE TITLE
grpc transcoding: need to refresh cached route after header changes

### ISSUE THREAD

**Issue by mattklein123** [lyft/envoy#1434]
See https://github.com/lyft/envoy/issues/1427

**Comment by lizan** [comment]
looked at #1274 again, shouldn't the route pre-calculated only if the connection manager see WebSocket Upgrade header?

**Comment by mattklein123** [comment]
No it pre-calculates now in all cases.

**Comment by lizan** [comment]
I meant should we change that behavior to calculate only in WebSocket path?

**Comment by mattklein123** [comment]
We can't, you need to calculate the route to know if it's a WS route. And if we calculate it (which is expensive) we might as well cache it. I always knew this might be a problem. IMO the fix is to provide a filter callback to force a route cache refresh.

**Comment by mattklein123** [comment]
We could potentially optimize this by only doing it if there is at least one WS route, but the problem still remains as an edge case. @rshriram we should probably do <- anyway. Basically make ConfigImpl know if there is at least 1 WS route and pivot on that.

**Comment by lizan** [comment]
Here is my initial thought:
Looked at the `if` block:
https://github.com/lyft/envoy/blob/master/source/common/http/conn_manager_impl.cc#L501

Other than the last [`else`](https://github.com/lyft/envoy/blob/master/source/common/http/conn_manager_impl.cc#L517), routes can be calculated after checking `websocket_requested`, and we can put that part in `else` into router, since filters might also change it, thoughts?

**Comment by lizan** [comment]
Also the current impl will allow HTTP/2 traffic to WS route, is that expected behavior? @rshriram

**Comment by rshriram** [comment]
I don't think so.. https://github.com/lyft/envoy/blob/master/source/common/http/conn_manager_impl.cc#L496 filters it for HTTP1 only. If you mean can a route table support HTTP/2 and websockets (for different routes), then yes. But that is normal behavior right?

**Comment by lizan** [comment]
Right, my question was HTTP2 downstream normal traffic to a route with
websocket.

**Comment by lizan** [comment]
I will make a PR soon to fix this along with the integration test to detect
this.

**Comment by rshriram** [comment]
Ah yes.. that would fail.
