### ISSUE TITLE
newbie: help with LDS (v1)

### ISSUE THREAD

**Issue by marcosrmendezthd** [lyft/envoy#1468]
Hi,

First of all, thanks for the great work! I'm trying to dynamically define tcp listeners to which I'm assigning ports for backend services. So I'm looking at getting CDS and LDS working. New to envoy, so if I'm on the wrong path let me know. So the clusters define the backends, the listeners define the front end port.

I've been able to get CDS working with the following configuration and an endpoint that exposes _/v1/clusters/{service_cluster}/{service_node}_. envoy picks up my dynamically defined clusters, but I'm unsure where to plug in LDS. I've already got a _/v1/listeners/{service_cluster}/{service_node}_ endpoint, but it doesn't seem to get called. Any pointers?

```
{
  "listeners": [],
  "admin": {
    "access_log_path": "/dev/null",
    "address": "tcp://0.0.0.0:8001"
  },
  "cluster_manager": {
    "clusters": [],
    "cds": {
      "refresh_delay_ms": 5000,
      "cluster": {
        "name": "my-cluster",
        "connect_timeout_ms": 250,
        "type": "static",
        "lb_type": "least_request",
        "hosts": [
          {
            "url": "tcp://ip:port"
          }
        ]
      }
    }
  }
}
```

The clusters endpoint is returning clusters like the ones below:

```
{
	"clusters": [{
			"name": "my-cluster",
			"connect_timeout_ms": 250,
			"type": "static",
			"lb_type": "least_request",
			"hosts": [{
				"url": "tcp://backend_ip:backend_port"
			}]
		}
	}
```

**Comment by mattklein123** [comment]
Sorry! Somehow I managed to not document the top level "lds" object in the documentation. I will fix this tomorrow morning:
https://github.com/lyft/envoy/blob/master/source/common/json/config_schemas.cc#L1173
https://lyft.github.io/envoy/docs/configuration/listeners/lds.html

**Comment by marcosrmendezthd** [comment]
we have lift off! thank you!

added the following to the top-level configuration

```  "lds": {
    "cluster": "my-cluster",
    "refresh_delay_ms": 5000
  },```
