### ISSUE TITLE
CLI log levels shouldn't just be a uint_t

### ISSUE THREAD

**Issue by jcoatgoogle** [lyft/envoy#148]
Right now, per --help

    -l <uint64_t>,  --log-level <uint64_t>
      Log level

This isn't the most helpful... IMO this should conform to what people are used to (info, fine, debug, etc) but perhaps the convention in C++ is different? Regardless, there should be some what to know what will get you what

**Comment by mattklein123** [comment]
Will fix

**Comment by mattklein123** [comment]
https://github.com/lyft/envoy/pull/160
