### ISSUE TITLE
replace openssl with boringssl

### ISSUE THREAD

**Issue by mattklein123** [lyft/envoy#152]
Officially replace openssl w/ boringssl and make boringssl the recommended TLS library.

@PiotrSikora any interest in owning this?

cc @louiscryan

**Comment by PiotrSikora** [comment]
I'll send some patches in a day or two... However, please note that this is gated on libevent release containing this fix: https://github.com/libevent/libevent/commit/6702da1a8ca6043aea662e191289869070e4f10d (unless you want to build against master?), because libevent must also be linked against BoringSSL, since Envoy uses libevent's `bufferevent`.

**Comment by mattklein123** [comment]
Hmm. For our internal build we can apply this patch. For the public build we could apply the patch inside the docker container, but that is suboptimal. Do you have any idea what the status is of a new libevent release? I poor option would be to fork libevent into lyft, apply the patch, and do a release and use that until there is an official libevent release.

**Comment by lizan** [comment]
@PiotrSikora With the code change (replacing SSL_CTX_ctrl and SSL_ctrl), it would still compile with OpenSSL, no? If so, can the code change happen before switching the build?

**Comment by PiotrSikora** [comment]
Last stable release (2.0.22) was on 2015-01-05, last beta release (2.1.6) was on 2016-08-26 and the previous one (2.1.5) was on 2015-01-05, so I wouldn't plan on a release containing that fix anytime soon.

Since Envoy is statically linked, shipping patched version of libevent seems reasonable.

**Comment by mattklein123** [comment]
OK. I think I'm leaning towards just forking libevent into lyft, applying the patch on top of 2.0.22 and doing a release, then consuming that in the public CI build with appropriate docs.

@lizan @PiotrSikora I don't have any experience with boringssl so am open to any guidance on how to best handle the switch from openssl and whether we still want to support openssl at least unofficially.

I mainly want to switch because I know that you all will help make sure we are up to date and secure if we are using boringssl. :)

**Comment by PiotrSikora** [comment]
There is no reason to not support both. They are mostly API compatible.

**Comment by mattklein123** [comment]
Per https://github.com/lyft/envoy/issues/168 I think we are probably going to stop using bufferevent in libevent, so I think we probably won't need the libevent patch. I need to implement direct openssl support using BIO, so will get that going in the next couple of weeks.

**Comment by rshriram** [comment]
I believe this is done by PR #163 ?

**Comment by mattklein123** [comment]
Not yet, we need to update the CI image and get on-boarded by Google for boringssl tracking/updates. I'm working on this offline.

**Comment by RomanDzhabarov** [comment]
https://github.com/lyft/envoy/pull/339 - third party image update

**Comment by mattklein123** [comment]
fixed
