### ISSUE TITLE
build: update docker image on every master commit that passes tests

### ISSUE THREAD

**Issue by mattklein123** [lyft/envoy#155]

**Comment by rshriram** [comment]
@mattklein123 this is easy IIRC. In dockerhub, there is a setup option that automatically builds the docker image anytime the master branch gets updated. https://docs.docker.com/docker-hub/github/ .

**Comment by WhileLoop** [comment]
If you are going to do this please tag the containers with something other than latest.

**Comment by mattklein123** [comment]
Need to also build all of the example images.

**Comment by mattklein123** [comment]
@junr03 per discussion in https://github.com/lyft/envoy/pull/416 as part of this work can we also get a script together for pushing the envoy-build image to dockerhub with a sha tag, then update do_ci.sh to explicitly use a tagged version of the build image.

**Comment by junr03** [comment]
@mattklein123 do we want to push the envoy-build image automatically (on a trvis build), or just have a script that we run locally when we update dependencies?

**Comment by mattklein123** [comment]
I think it can be manual, but we should push the image tagged at the SHA it was built at, and then reference that tag in do_ci.sh. Then we should remove the latest image so that all builds are explicitly version locked.

**Comment by junr03** [comment]
@mattklein123 ok sounds good. In that case do we also want to version lyft/envoy, or keep the understanding that we push on every push to master that passes tests?

**Comment by WhileLoop** [comment]
I would like to see tagged releases if possible.

**Comment by junr03** [comment]
@WhileLoop just to be clear, are you talking about versioned releases like lyft/envoy:1.0.0, or tagged releases with the SHA like lyft/envoy:SHA?

**Comment by junr03** [comment]
For the time being we are going to have:
1. Tagged images for `envoy-build` with the commit they are built from. This is going to be used to run CI.
2. On every PR, the docker examples are going to be executed and test to run against the PRs code.
3. On every green push to master the `envoy` image is going to be pushed with the `latests` tag.

**Comment by junr03** [comment]
All of this is implemented in https://github.com/lyft/envoy/pull/408
