### ISSUE TITLE
Please support routing HTTP requests by method (GET, POST, etc)

### ISSUE THREAD

**Issue by jmillikin-stripe** [lyft/envoy#1553]
This is useful when using Envoy as an authenticating proxy -- we can apply less restrictive rules to HEAD and GET requests vs other, possibly mutating methods.

**Comment by mattklein123** [comment]
This is already supported. Do a header match on the ":method" header: https://lyft.github.io/envoy/docs/configuration/http_conn_man/route_config/route.html#headers

(This is a pretty common question and we should probably spell it out in that section if you feel like doing a doc PR).
