### ISSUE TITLE
Unable to perform TLS origination to public Web sites

### ISSUE THREAD

**Issue by vadimeisenbergibm** [lyft/envoy#1555]
I tried to perform TLS origination to google.com, httbin.org, github.com. tumi.com and ibm.com. Only for google the communication was successful.

Here are two example configurations:
[configuration for httbin.org](https://gist.github.com/vadimeisenbergibm/44a622f913de94c73125af0c52429c99)
[configuration for github.com](https://gist.github.com/vadimeisenbergibm/2c739e67868ffe68bce15bde9bb6d27d)

Using Envoy's logging I see that in both cases a handshake error happens in source/common/ssl/connection_impl.cc. 

I can access the both sites by curl, from the account on which the envoy instance runs.

Can anybody advise on the example configurations? Can anybody provide an example of a working configuration with TLS origination to `httbin.org`, as a reference?

**Comment by mattklein123** [comment]
Per Gitter my quick guess would be you need to setup client side SNI. I would test with "openssl s_client".

**Comment by mattklein123** [comment]
@PiotrSikora see Gitter. AFAICT if "sni" is set I think it should work. Not sure what's going on. Do you mind taking a quick look? (FYI I don't think we have any SNI tests in public repo since we don't have server side SNI support, hopefully we can fix that when you implement).

**Comment by PiotrSikora** [comment]
@vadimeisenbergibm it works for me just fine using [your configuration for httpbin.org](https://gist.github.com/vadimeisenbergibm/44a622f913de94c73125af0c52429c99/aeff260717e51f4dee6cac7a843b7dd54466eaa6):

```
$ curl -vk http://127.0.0.1:443/headers -H"Host: httpbin.org:443"
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 443 (#0)
> GET /headers HTTP/1.1
> Host: httpbin.org:443
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 200 OK
< server: envoy
< date: Mon, 28 Aug 2017 19:04:05 GMT
< content-type: application/json
< access-control-allow-origin: *
< access-control-allow-credentials: true
< x-powered-by: Flask
< x-processed-time: 0.000670909881592
< content-length: 133
< via: 1.1 vegur
< x-envoy-upstream-service-time: 297
<
{
  "headers": {
    "Accept": "*/*",
    "Connection": "close",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.52.1"
  }
}
* Curl_http_done: called premature == 0
* Connection #0 to host 127.0.0.1 left intact
```

which version / commit of Envoy are you using?

**Comment by vadimeisenbergibm** [comment]
@PiotrSikora I use lyft/envoy:latest docker image

**Comment by PiotrSikora** [comment]
@vadimeisenbergibm it also works fine for me from within the `lyft/envoy:latest` container:

```
$ curl -o /tmp/httpbin_org_proxy.json https://gist.githubusercontent.com/vadimeisenbergibm/44a622f913de94c73125af0c52429c99/raw/aeff260717e51f4dee6cac7a843b7dd54466eaa6/envoy_config_httpbin.json
$ docker run --rm -it -v /tmp:/tmp lyft/envoy:latest /bin/bash
root@f76dd00beb03:/# /usr/local/bin/envoy -c /tmp/httpbin_org_proxy.json &
root@f76dd00beb03:/# apt-get install -y curl
root@f76dd00beb03:/# curl -v http://127.0.0.1:443/headers -H"Host: httpbin.org:443"
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 443 (#0)
> GET /headers HTTP/1.1
> User-Agent: curl/7.35.0
> Accept: */*
> Host: httpbin.org:443
>
< HTTP/1.1 200 OK
* Server envoy is not blacklisted
< server: envoy
< date: Mon, 28 Aug 2017 20:00:56 GMT
< content-type: application/json
< access-control-allow-origin: *
< access-control-allow-credentials: true
< x-powered-by: Flask
< x-processed-time: 0.000629901885986
< content-length: 133
< via: 1.1 vegur
< x-envoy-upstream-service-time: 301
<
{
  "headers": {
    "Accept": "*/*",
    "Connection": "close",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.35.0"
  }
}
* Connection #0 to host 127.0.0.1 left intact
```

Is there any intercepting proxy between you & public Internet?

Also, could you provide repeatable steps of what are you doing in the container, to make sure that the issues is not elsewhere (e.g. iptables)?

**Comment by PiotrSikora** [comment]
I think the issue might be the short connection timeout in your CDS config, i.e.:

    "connect_timeout_ms": 250,

Could you increase it to `2000` (i.e. 2 seconds) and see if the issue is still there?

**Comment by vadimeisenbergibm** [comment]
@PiotrSikora you are right - the issue was with the short connection timeout. I increased it to 2500, and both `httpbin.org` and `github.com` started to work. Thanks a lot!

@mattklein123 Additional problem was SNI for `httpbin.org`, as you correctly guessed. `github.com` does not require SNI.

Thanks a lot for your help. I have updated the configurations at the links of this issue.

**Comment by ldemailly** [comment]
how do you set "sni" on the client ? that may solve #2670
