### ISSUE TITLE
fail build in more obvious way if missing deps

### ISSUE THREAD

**Issue by mattklein123** [lyft/envoy#1589]
https://groups.google.com/forum/#!topic/envoy-users/MPLgCsj0zrQ

**Comment by htuch** [comment]
Part of the problem is the Bazel build doesn't hard fail when the `repository_rule` executes `fail`, see https://github.com/bazelbuild/bazel/issues/3683.

**Comment by htuch** [comment]
New failure message in PR 
![screen shot 2017-09-04 at 12 40 57 pm](https://user-images.githubusercontent.com/10914751/30034498-f04e2dea-916f-11e7-9ab4-000c37f62307.png)
