### ISSUE TITLE
Current lyft/envoy:latest Docker Hub image is based on Ubuntu 14.04. Breaks your own examples due to missing Python >=3.5 dependency.

### ISSUE THREAD

**Issue by zeroum** [lyft/envoy#1597]
Following the guide in https://lyft.github.io/envoy/docs/install/sandboxes/front_proxy.html

lyft/envoy:latest tag was b2114cd959c8e4231006c4b8b8150df7576833d2

$ pwd
envoy/examples/front-proxy
$ docker-compose up --build -d

...
Building service2
Step 1/8 : FROM lyft/envoy:latest
...
Get:1 http://security.ubuntu.com **trusty**-security InRelease [65.9 kB]
...
Step 3/8 : RUN pip install -q Flask==0.11.1
 ---> Running in b4b92d0d38ad
Compiling /tmp/pip_build_root/Jinja2/jinja2/asyncfilters.py ...
  File "/tmp/pip_build_root/Jinja2/jinja2/asyncfilters.py", line 7
    async def auto_to_seq(value):
            ^
SyntaxError: invalid syntax

**Comment by marcosrmendezthd** [comment]
@mattklein123 ^^^^ :)
