### ISSUE TITLE
tracing: swap Lightstep C++ bindings for OT C++ bindings

### ISSUE THREAD

**Issue by mattklein123** [lyft/envoy#172]
Requires OT C++ library to be finalized.

cc @bensigelman

**Comment by bensigelman** [comment]
(Also cc @jmacd)

The only challenge will be the part of the code that does a flush... OT won't / shouldn't have an opinion about serialization formats, esp for out-of-band data, so some sort of cast to the LightStep tracer will be necessary there... but all of the actual Span creation, tagging, etc, can and should be pure OpenTracing code.

@jmacd: how much has the lightstep Tracer+Span interface diverged from whatever's at head in OT-CPP?

**Comment by jmacd** [comment]
My proposal is to factor the existing lightstep API into three parts, opentracing API, basictracer implementation, and lightstep recorder. This approach would defer any attempt to coordinate with the C++98 work that was done in the openctracing-cpp repo.

**Comment by mattklein123** [comment]
@bensigelman @jmacd will defer to both of you on best way of moving forward. Flexible on timeline also if there is more work to do on C++ OT first.

**Comment by mattklein123** [comment]
I'm going to close this as won't fix until there is a compelling reason to implement.
