### ISSUE TITLE
Document the minimal interfaces for providing new discovery modes

### ISSUE THREAD

**Issue by timperrett** [lyft/envoy#185]
@mattklein123 as we discussed last night, if we could get some documentation that shows the bare minimum interface(s) for providing a new mode of discovery, that would be excellent! Preferably it would be something that is not mixed up with the DNS part, which is far more complicated. Having such documentation would make contributing new modes of discovery far easier. 

Thanks in advance.

**Comment by mattklein123** [comment]
Yup will do.

**Comment by mattklein123** [comment]
It seems like everyone is getting on the SDS/CDS/RDS bandwagon so I'm going to close this out. I would like to revisit general plugin documentation in depth at a later time.
