### ISSUE TITLE
Support for consistent hashing lb 

### ISSUE THREAD

**Issue by rshriram** [lyft/envoy#197]
This is an enhancement request.
Need a load balancing policy that can route based on ketama hash of a HTTP header field (or source IP:port). This is useful in situations where a cache is sharded across a cluster of hosts. Incoming requests for a specific set of data can be routed to the same host if a particular HTTP header is present.

**Comment by mattklein123** [comment]
Thanks for logging. We plan on doing either ketama or maglev. At least on the Lyft side this probably won't get done till Q1 but happy to have a contribution if anyone wants to help out.
