### ISSUE TITLE
envoy binary file size - currently 127MB

### ISSUE THREAD

**Issue by ramtej** [lyft/envoy#240]
Hi guys, 

I;m thinking about to use envoy in a kubernetes setup. 

One of the challenges in such a setup is to keep the docker / rtk container image size small and therefore I was a bit surprised that the envoy binary is about 127 MB.

However, I was able to "shrink" the binary down to about 8 MB using the ELF "strip" approach : 

`/tmp$ strip -S --strip-unneeded --remove-section=.note.gnu.gold-version --remove-section=.comment --remove-section=.note --remove-section=.note.gnu.build-id --remove-section=.note.ABI-tag envoy`

-rwxr-xr-x 1 jj jj 127M Nov 22 20:17 envoy.orig
-rwxr-xr-x 1 jj jj 7,7M Nov 22 20:18 envoy

The question is, what makes the binary such large ?

Thank you. 

Cheers, 
jj

**Comment by mattklein123** [comment]
The default build includes debug symbols and is statically linked. If you strip symbols that's what takes you down to 8MB or so. If you want to go down further than that you should dynamically link against system libraries.

FWIW, we haven't really focused very much on the build/package/install side of things. I'm hoping the community can help out there. Different deployments are going to need different kinds of compiles.

**Comment by mattklein123** [comment]
cc @enricoschiattarella @louiscryan I think you are already probably thinking about ^^^ not sure if you have any thoughts.

**Comment by ramtej** [comment]
Hi Matt,

thank you for your feedback !

Agree, different deployment scenarios has different requirements. I also like the static linking approach, to keep things consistent and independent. 

At least for my usecase the "strip" approach fine, but evtl. a kind of "included" solution will be better. 

Cheers, 
jj

**Comment by moderation** [comment]
I think statically linked is important as if you wanted to run in a Docker container you could in theory create a minimal image using `from scratch`. I haven't tested this yet.

**Comment by ramtej** [comment]
yes, this is exactly what I;m doing and therefore the dynamic approach will not work. Also such a critical component should be self-contained.

**Comment by mattklein123** [comment]
At the very least we can put in a cmake option to strip debug symbols. That is easy to do.

**Comment by mattklein123** [comment]
fixed
