### ISSUE TITLE
Consider not use OpenSSL to base64 encode

### ISSUE THREAD

**Issue by lizan** [lyft/envoy#301]
BIO_f_base64 is deprecit in BoringSSL, should we consider use another implementation?

- linearize the buffer and use base64 encoder from nghttp2 sounds reasonable

cc @PiotrSikora

**Comment by mattklein123** [comment]
From a quick scan I don't think the nghttp2 base64 implementation is exported from the main library. We could potentially copy that code. Not sure if there are better options. Definitely happy to use something other than BIO here.

**Comment by mattklein123** [comment]
@tatsuhiro-t any interest in exposing the base64 encoder in the nghttp2 library? :)

**Comment by lizan** [comment]
Or I can simply just implement one if you think it is fine.

**Comment by mattklein123** [comment]
I'm happy with whatever as long as it has tests. @lizan feel free to take this one.

**Comment by tatsuhiro-t** [comment]
@mattklein123 No plan to expose base64 encoder.  It is MIT licensed, and header only. It is relatively easy to import it to envoy.  Implementing it from scratch is also not hard.

**Comment by lizan** [comment]
Closed via #306
