### ISSUE TITLE
docs: comparison to nghttp2

### ISSUE THREAD

**Issue by andrewwebber** [lyft/envoy#310]
Without going into the code it is difficult understand the following question:

- nghttp2 usage? Is Envoy a like for like rewrite/implementation or to what extent is Envoy based on the nghttp2 library

**Comment by mattklein123** [comment]
nghttp2 is a library that implements the http/2 protocol codec. Envoy uses nghttp2 for http/2 codec support. Beyond the fact that Envoy uses nghttp2 as a library for a portion of its functionality the two projects are not comparable.

**Comment by andrewwebber** [comment]
This is very useful information, thank you. nghttp2 also have a proxy application. I was currently using nghttpx proxy application and trying to compare it to Envoy. Would you say it is work comparing [nghttpx](https://nghttp2.org/documentation/nghttpx-howto.html)

**Comment by mattklein123** [comment]
Sure we can do a comparison to nghttpx. At a high level nghttpx is an example HTTP/2 proxy written on top of the nghttp2 library. It can transparently proxy HTTP/1 <-> HTTP/2 and has a variety of other proxy features. Envoy is largely a superset of nghttpx (it contains substantially more features around routing, advanced load balancing, stats, service discovery, etc.). I don't personally consider nghttpx a production ready proxy solution but more of an example.

**Comment by andrewwebber** [comment]
I agree with your notion of Envoy being a superset of nghttpx. I think it would be great to add this to the documentation section. I think many notice gRPC users find the gRPC website recommendation of using nghttpx. Envoy looks far superior.

**Comment by mattklein123** [comment]
Sure will add. I'm going to reopen this to track editing the docs.
