### ISSUE TITLE
Add Listener Discovery Service (LDS) API

### ISSUE THREAD

**Issue by mattklein123** [lyft/envoy#315]
Natural progression behind SDS/CDS/RDS. Low priority but opening for visibility.

cc @enricoschiattarella 

Work items:

- [ ] make listen() errors graceful and unified between initial startup and dynamic add.

**Comment by mattklein123** [comment]
Some rough implementation notes for this one:
1) Refactor the listener config implementation to be its own standalone class: https://github.com/lyft/envoy/blob/master/source/server/configuration_impl.h#L86. It shouldn't have any explicit dependencies on the main config.
2) The stat scope used inside this class needs to be correctly plumbed through so that it is used on all listener bound stats. Essentially, the filter factory for both network filters as well as HTTP listeners need to be passed the listener stat scope for use in creating filters: https://github.com/lyft/envoy/blob/master/source/server/configuration_impl.h#L27
3) Much like we added add/remove listener APIs to the cluster manager, the main server will need to have similar APIs added. This will involve a refactor of the code in https://github.com/lyft/envoy/blob/master/source/server/server.cc#L171 that initializes listeners on each worker, to to RCU like fanout just as the cluster manager code does. The same code used for hot restart to lookup existing listen sockets can be used when adding/overwriting listeners.
4) Need to add an actual fetcher for LDS much like CDS, which fetches and then decides whether to call the server APIs to add/remove listeners.
5) Optimally, initialization of listeners fetch from CDS should be done last, after both CDS and RDS. I am going to redo how init happens when I do RDS so this should't be that hard.

**Comment by mattklein123** [comment]
FYI, this is potentially being worked on. Please reach out to me if you are thinking about working on this or need this imminently.

**Comment by wattli** [comment]
One useful scenario is cert rotation, i.e., cert changes periodically, while cert name is fixed. LDS should be able to detect cert content change.

**Comment by mattklein123** [comment]
Assigning to myself for now until we figure out for sure who is implementing this.

**Comment by mattklein123** [comment]
@kyessenov @rshriram @htuch @timperrett  (and whoever else feels like weighing in): I'm actually implementing the dynamic logic now (yay) and I have a question about semantics.

The way I'm implementing this is that listeners will need to have a unique name that describes them. (This is to handle the port 0 binding case, in which we cannot use address to differentiate). How should we handle port conflicts for dynamic listeners? Should we force updated listeners with the same unique name to have the same address and otherwise fail?

My inclination is to do the following:
1) Updated listeners with the same name must have the same address, otherwise the update will fail.
2) A dynamic listener that tries to bind to an already in use address will fail (same as today). I need to check the logic for listeners that do not bind but that should fail too. So basically, a listener must be unique across both name and final address (after port 0 resolution in the binding case).

Let me know what everyone thinks about this.

**Comment by htuch** [comment]
1 and 2 seem reasonable. Is there a well defined ordering for how listeners are intialized that would allow the behavior in 2 to be predicted? Or is it just a fundamental misconfiguration to bind multiple listeners to an address, and we allow the implementation the freedom to chose who wins or loses?

**Comment by timperrett** [comment]
Retaining the same port binding where the identifier is the same, seems eminently reasonable.

**Comment by mattklein123** [comment]
@htuch as the listeners is an array, I plan on keeping the order deterministic. (This is actually required for test sanity anyway with the port 0 substitution). In v2 it's still an array, so everything should be predictable.

@kyessenov as an aside, I just looked at the original_dst logic, and right now we allow multiple port 0 listeners that do not bind, which makes no sense at all (and in fact the search will only ever find the first one). I'm going to fix this,

**Comment by mattklein123** [comment]
I'm calling this complete. If there are further issues, etc. we will open new issues.
