### ISSUE TITLE
HTTP2 Load balancing affinity

### ISSUE THREAD

**Issue by andrewwebber** [lyft/envoy#320]
This could be a beginner question so I apologise.

It was not clear to me in the documentation how HTTP2 load balancing works. 

As new HTTP2 requests come in from a single client on a HTTP2 connection to a envoty route does each client request continue to communicate with the original backend instance (say 7 of 9) or does each request within a client connection to Envoy get load balanced to all 9 backend instances of a cluster. 

Is this also configurable as I could imagine many architecture scenarios where different affinity makes sense

**Comment by mattklein123** [comment]
Requests get load balanced to all backends depending on the load balancing policy. Currently we do not support any consistent hashing load balancing policies, however we will support hash based load balancing for HTTP based on a header "soon" (~4-6 weeks).

**Comment by andrewwebber** [comment]
This is great information, thank you.

Currently a bidirectional gRpc stream seems to simulate session affinity although it's application is very limited

**Comment by mattklein123** [comment]
Going to close this out, let us know if you have further questions on this topic.
