### ISSUE TITLE
Allow for simple TCP healthcheck

### ISSUE THREAD

**Issue by moderation** [lyft/envoy#336]
Send and receive packets are required when configuring TCP health checks in the Cluster Manager.  Documentation at https://lyft.github.io/envoy/docs/configuration/cluster_manager/cluster_hc.html#config-cluster-manager-cluster-hc

It will be useful to allow pure TCP healthchecks without the requirement to send and receive bytes. Examples would be health checking CockroachDB on port 26257 or a PostgreSQL DB.

Gitter discussion at https://gitter.im/lyft/envoy?at=586ea8b6c02c1a3959efa34c

**Comment by mattklein123** [comment]
@danielhochman another useful warm up
