### ISSUE TITLE
Need working service discovery Example Config.

### ISSUE THREAD

**Issue by irfn** [lyft/envoy#367]
I have given Service discovery a try via following config in cluster manager.
I am assuming that following should result in a call `GET http://192.168.1.1:8080/v1/registration/my-service` as per reference Implementation (https://github.com/lyft/discovery)

```
"cluster_manager": {
      "sds": {
          "cluster": {
              "name": "fooServiceDiscovery",
              "type": "static",
              "connect_timeout_ms": 250,
              "lb_type": "round_robin",
              "hosts": [
                  {
                      "url": "tcp://192.168.1.1:8080"
                  }
              ]
          },
          "refresh_delay_ms": 100
      },
      "clusters": [
          {
              "name": "myServiceGrpc",
              "type": "sds",
              "connect_timeout_ms": 250,
              "lb_type": "least_request",
              "service_name":"my-service",
              "features": "http2",
              "ssl_context": {
                  "alpn_protocols": "h2"
              }
          }
      ]
  }
```

I could not get this to work. There was no call made to the service discovery server. Please help debug this and provide an example.

**Comment by mattklein123** [comment]
This is an initialization bug. I will fix.

In the meantime, to unblock yourself, switch the SDS cluster type to "strict_dns" and it will work.

**Comment by irfn** [comment]
@mattklein123  Thanks for providing the workaround. I confirm that "strict_dns" setting for sds worked.

**Comment by irfn** [comment]
@mattklein123 can you tell me if there is downside of using strict_dns for service discovery in production. Ill actually not be using dns. Ill be using an ip address. 
I have implemented my own "agent" which will translate the consul agent api to lyft reference api. Ill be configuring the ip to this agent.

**Comment by mattklein123** [comment]
@irfn there is no downside other than a bit extra CPU when we make a DNS query for a static IP. I am however fixing this bug in the next few days in the context of also fixing https://github.com/lyft/envoy/issues/330
