### ISSUE TITLE
v2 gRPC/JSON APIs for SDS/CDS/RDS/LDS/load reporting

### ISSUE THREAD

**Issue by irfn** [lyft/envoy#368]
While a polling api and a low enough `refresh_delay_ms` does the trick, i have been trying to move to model where changes in deployment /services  would raise an event. This way we could set the periodic service discovery via `refresh_delay_ms` to a big number and rely on events for a more realtime update.
I would suggest an admin like api such as `/clusters/discover` etc. that can be triggered externally  eg:  `consul watch` could be used for consul. This approach will rely on that external tool to be in sync or poll for changes etc. Envoy itself doesn't have to have to do polling.
This approach can then be combined with outlier detection to have a low overhead service discovery.

**Comment by mattklein123** [comment]
The entire design of Envoy relies on eventual consistency. Polling is much simpler and less failure prone than a trigger based API, so it's unlikely that we will ever implement anything like this.

With that said, we are likely to eventually implement gRPC streaming APIs for SDS/CDS/RDS which should give much more push like behavior given persistent connections. I'm going to rename this issue to that effect to track that.

**Comment by 0x1997** [comment]
It's simpler to make the timeout in [RestApiFetcher::refresh](https://github.com/lyft/envoy/blob/c45f817ec841d2ed1ba3d4a74ca76fe11173c9e8/source/common/http/rest_api_fetcher.cc#L51) configurable so SDS/CDS/RDS can support long polling.

**Comment by mattklein123** [comment]
@amb67 per meeting do you want to own the initial proto proposal here? It's probably easiest to start in a good doc then we can move the final spec here when it's ready.

**Comment by amb67** [comment]
Yes, I will publish the doc in a couple of weeks and we can iterate on it.

**Comment by mattklein123** [comment]
For those following along, we will be iterating on the v2 APIs in the https://github.com/lyft/envoy-api repo where we will build out real protos, JSON versions, etc.

**Comment by htuch** [comment]
This is now tracked under the label "v2 API", https://github.com/lyft/envoy/issues?page=1&q=is%3Aissue+is%3Aopen+label%3A%22v2+API%22, so closing out.
