### ISSUE TITLE
Supports GRPC streaming based on Asyn HTTP2 client.

### ISSUE THREAD

**Issue by fengli79** [lyft/envoy#381]
Pull request https://github.com/lyft/envoy/pull/353 is going to support async stream HTTP2 client in envoy.
After that, I'm going to implement the GRPC client on top of it to enable GRPC streaming calls.

**Comment by lizan** [comment]
Is that going to support generated grpc code or not?

**Comment by fengli79** [comment]
It's not for generated grpc code. It's for generic calls.

**Comment by mattklein123** [comment]
@fengli79 I know it's a question for the gRPC folks, but is there any chance of getting it eventually working with gRPC compiled code similar to how we use the deprecated generic RPC proto stuff here: https://github.com/lyft/envoy/blob/master/source/common/grpc/rpc_channel_impl.h? That would be really neat to get working in the future.

**Comment by fengli79** [comment]
We don't have plan to do that yet, however I would vote for yes if it's
highly desired by community.

**Comment by mattklein123** [comment]
@fengli79 I started this branch to do zero copy for proto encode/decode:
https://github.com/lyft/envoy/tree/grpc_perf

I don't have time to finish this right now, but if you find it useful for the streaming gRPC stuff feel free to build on it.

**Comment by mattklein123** [comment]
Per offsite meeting, we are going to integrate the full gRPC stack into Envoy to make outbound calls. It doesn't sound like a tremendous amount of work. I'm going to won't fix this for now and open a new issue on that.

**Comment by fengli79** [comment]
OK, please assign it to me once you create it.
