### ISSUE TITLE
Support custom hook for HTTP access log

### ISSUE THREAD

**Issue by qiwzhang** [lyft/envoy#393]
HTTP access log is quick useful for many applications. They will like to provide custom hooks to intercept the request_info after response data is send but before all data structures are gone.  It also needs a way for DecoderFilter or EncoderFilter to create some data objects for the request and pass them to custom access_log hooks.

**Comment by mattklein123** [comment]
@RomanDzhabarov can you meet with @qiwzhang offline and come up with a proposal to add back to this issue. As I see it, there are several options:
1) Use a "tracer" vs. a direct hook in the active stream destructor path.
2) Add a new extensibility mechanism independent from filters, to add post request hooks.
3) (Possibly easiest and most straightforward), allow filters to register for a post request hook callback. They would be passed request info, etc. and could make calls. The assumption here is that the hook can not block destruction, but can make an async call for example via AsyncClient.
