### ISSUE TITLE
JSON schema validation failed with an existing config file.

### ISSUE THREAD

**Issue by qiwzhang** [lyft/envoy#399]
After pull in changes from https://github.com/lyft/envoy/pull/365,  my config file doesn't work any more.

Here is the error:

[2017-01-31 10:47:00.258][10775][critical][main] error initializing configuration 'src/envoy/prototype/envoy-esp.conf': JSON object doesn't conform to schema.
 Invalid schema: #/properties/filters.
 Invalid keyword: minItems.
 Invalid document key: #/filters

Process finished with exit code 1

The error message is not helping.

Here is my config file:

{
    "admin": {
        "access_log_path": "/dev/stdout",
        "port": 9001
    },
    "cluster_manager": {
        "clusters": [
            {
                "connect_timeout_ms": 5000,
                "hosts": [
                    {
                        "url": "tcp://localhost:8080"
                    }
                ],
                "lb_type": "round_robin",
                "name": "service1",
                "type": "strict_dns"
            },
            {
                "connect_timeout_ms": 5000,
                "hosts": [
                    {
                        "url": "tcp://localhost:8081"
                    }
                ],
                "lb_type": "round_robin",
                "name": "api_manager",
                "type": "strict_dns"
            }
        ]
    },
    "listeners": [
        {
            "bind_to_port": true,
            "filters": [],
            "port": 9092,
            "use_original_dst": true
        },
        {
            "bind_to_port": false,
            "filters": [
                {
                    "config": {
                        "access_log": [
                            {
                                "path": "/dev/stdout"
                            }
                        ],
                        "codec_type": "auto",
                        "filters": [
                            {
                                "config": {
                                    "server_config": "src/envoy/prototype/server_config.pb.txt",
                                    "service_config": "src/envoy/prototype/generic_service_config.json"
                                },
                                "name": "esp",
                                "type": "both"
                            },
                            {
                                "config": {},
                                "name": "router",
                                "type": "decoder"
                            }
                        ],
                        "route_config": {
                            "virtual_hosts": [
                                {
                                    "domains": [
                                        "*"
                                    ],
                                    "name": "backend",
                                    "routes": [
                                        {
                                            "cluster": "service1",
                                            "prefix": "/",
                                            "timeout_ms": 0
                                        }
                                    ]
                                }
                            ]
                        },
                        "stat_prefix": "ingress_http"
                    },
                    "name": "http_connection_manager",
                    "type": "read"
                }
            ],
            "port": 9090
        }
    ],
    "tracing_enabled": "true"
}

**Comment by RomanDzhabarov** [comment]
on a separate unrelated to the current issue note,
>> "tracing_enabled": "true"
this is incorrect as well, if you do not want LightStep tracing just remove that line (if you do, you'll have to have "tracing" configuration under connection manager)

**Comment by qiwzhang** [comment]
Thanks.  will remove "tracing_enabled": "true"

**Comment by ccaraman** [comment]
Thank you for reporting this. The config is failing because port 9092 has an empty list for filters. This is a bug in the schema where it checks for at least one item in the filters. I'll update the schema and documentation now.

**Comment by ccaraman** [comment]
One thing to note, the connection will be closed if there are no filters for a listener.

**Comment by qiwzhang** [comment]
Yes, understood.  That is our intend.  Thanks.
