### ISSUE TITLE
docs: custom filter build strategy

### ISSUE THREAD

**Issue by mattklein123** [lyft/envoy#404]

**Comment by mattklein123** [comment]
@htuch this is related to the comment that I just posted in the doc that is circulating around build stuff. If we switch to bazel we need a general strategy for compiling/linking in private filters and other code.

**Comment by htuch** [comment]
Ack, I'll add some coverage of this in the build proposal doc.

**Comment by mattklein123** [comment]
https://github.com/htuch/envoy-consumer

Need to figure out how/where to make the official.

**Comment by htuch** [comment]
Should also add a version (or indirect) to https://github.com/lyft/envoy/blob/master/bazel/DEVELOPER.md to help folks get bootstrapped with Bazel. @rshriram

**Comment by htuch** [comment]
https://github.com/lyft/envoy-filter-example is now populated. @mattklein123 @rshriram want to take a look and let me know what to add further? I didn't do a PR on this as this was just the initial checkin.

**Comment by mattklein123** [comment]
@htuch that looks awesome to me. I think we should just do some doc linking and it's good enough for now and can just see what Qs people ask. I would at minimum add a link to from here: https://lyft.github.io/envoy/docs/extending/extending.html
