### ISSUE TITLE
support  opaque configuration settings on route

### ISSUE THREAD

**Issue by wgallagher** [lyft/envoy#413]
For filters that need to act on a per-route basis, it would be useful to support a per-route configuration mechanism.  This config would be opaque to the envoy server itself but accessible to filters through an 'options' array of key-value pairs defined on route:

For example:

 {
    "prefix": "/my/route",
    "cluster": "mycluster",
    "options": [
       "my_filter_specific_confing": "some value"
    ]
}

**Comment by mattklein123** [comment]
@rshriram do you have any additional thoughts on ^ This seems generally useful to me.

@wgallagher personally, I might rename "options" to "opaque_options" just to make it more clear that these are not inspected by the main server. But I could go either way.

**Comment by rshriram** [comment]
Yes this is indeed very useful. I have been wanting to do something similar for the fault injection filter that would allow faults to be injected per route (in a catch all virtual host *).

In terms of the naming, why not just call it filters itself? Won't the semantics be clear then that this is not used for route selection but rather applied post routing?

An additional benefit of this is that these route specific filters would now be available as part of RDS.

**Comment by RyanMcG** [comment]
Any additional thoughts on this? Can we move forward with @rshriram's suggestion (`filter_options`)?

**Comment by mattklein123** [comment]
We can finalize the name once the PR is ready. The general concept is fine.
