### ISSUE TITLE
dns: de-dup returned entries

### ISSUE THREAD

**Issue by mattklein123** [lyft/envoy#433]
This was raised here: https://github.com/lyft/envoy/issues/431

If DNS returns the same entry multiple times, we will keep adding a host and effectively leak. Either the DNS impl itself should dedup, or the dymamic cluster add/remove code should do it.

cc @htuch

**Comment by htuch** [comment]
To what extent does order and multiplicity matter? Could we just pass a set to ResolveCb instead of a list in DnsResolver? Might the upper level cluster code use multiplicity to influence weight or order to determine preference?

**Comment by mattklein123** [comment]
Order doesn't currently matter, but the code in:
https://github.com/lyft/envoy/blob/master/source/common/upstream/upstream_impl.cc#L273

Does not correctly handle duplicates.

IMO, it would be better to fix the above code since that will cover not only DNS, but SDS, etc. also, and dealing with duplicates is really an envoy "problem" and not a DNS problem.
