### ISSUE TITLE
Envoy Config: Remove redundant config value checks

### ISSUE THREAD

**Issue by ccaraman** [lyft/envoy#454]
There are many config value checks across the code base that are no longer necessary due to schema validation. Example:  https://github.com/lyft/envoy/blob/master/source/common/http/filter/fault_filter.cc#L25

In addition, we should see if the schema can be improved to remove more of those config values.

**Comment by mattklein123** [comment]
There are a few cases also where we lookup JSON values in initializer lists before we actually run the validation code. Can we also make sure that we always run the validator before the first lookup in the object.

**Comment by ccaraman** [comment]
This issue should include work to look into setting defaults in the Json Schema.

**Comment by ccaraman** [comment]
Identify duplicated schemas and move checks to more central location such as `ssl_context` in Json::Schema::LISTENER_SCHEMA and Json::Schema::CLUSTER_SCHEMA.

**Comment by ccaraman** [comment]
Remove else catch alls ex: https://github.com/lyft/envoy/blob/721586f5844fdd5bc6a8a65243e38a5711c6ac34/source/common/router/router_ratelimit.cc#L89

**Comment by mattklein123** [comment]
@danielhochman there is already an internal JIRA tracking this one.
