### ISSUE TITLE
build: get gold incremental linking to work

### ISSUE THREAD

**Issue by mattklein123** [lyft/envoy#467]
Would be nice to get incremental linking using gold to work.

**Comment by mattklein123** [comment]
@htuch in the docker container, the following works to link, but then crashes (in a very strange way) when running envoy-test. If I remove --incremental it works fine in the docker container.

On my own machine, which is Ubuntu 16 and gcc 5.4, I can't get it to link incrementally at all (I get a relocation error). Though on my own machine, I can do a normal link with gold and the tests work fine.

```
mklein@localhost:~/Source/envoy-private/envoy$ git diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index b951d4f..17996ad 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -7,7 +7,7 @@ include(thirdparty.cmake)
 
 # Setup build ID via the linker. Also, statically link GCC libraries to lock GCC version.
 execute_process(COMMAND git -C ${CMAKE_SOURCE_DIR} rev-parse --sq HEAD OUTPUT_VARIABLE GIT_COMMIT WORKING_DIRECTORY ${PROJECT_SOURCE_DIR})
-set(CMAKE_EXE_LINKER_FLAGS "-Wl,--build-id=0x${GIT_COMMIT} -static-libstdc++ -static-libgcc ${ENVOY_EXE_EXTRA_LINKER_FLAGS} ${CMAKE_EXE_LINKER_FLAGS}")
+set(CMAKE_EXE_LINKER_FLAGS "-fuse-ld=gold -fno-use-linker-plugin -Wl,--incremental -Wl,--build-id=0x${GIT_COMMIT} -static-libstdc++ -static-libgcc ${ENVOY_EXE_EXTRA_LINKER_FLAGS} ${CMAKE_EXE_LINKER_FLAGS}")
 
 include_directories(${PROJECT_SOURCE_DIR}/include)
 include_directories(${PROJECT_BINARY_DIR}/source)
```

**Comment by htuch** [comment]
It looks like incremental linking with gold and C++ exceptions doesn't work. See recent posts at https://sourceware.org/bugzilla/show_bug.cgi?id=13442 and https://www.cygwin.com/ml/binutils/2016-11/msg00260.html. It comes down to a missing .eh_frame_hdr section, which I can confirm with readelf in the Docker image with the above patch.

**Comment by htuch** [comment]
Can we close this given #415? For dev and test builds, we can use dynamic linking for both tests and the Envoy binary, which seems fast enough with gold. The static link for release and CI use doesn't really need to be the that fast.

**Comment by mattklein123** [comment]
Sure sounds good. Closing.
