### ISSUE TITLE
perf: nghttp2 memory use

### ISSUE THREAD

**Issue by mattklein123** [lyft/envoy#471]
nghttp2 ends up using a large % of process memory, I believe mostly due to this issue:
https://github.com/nghttp2/nghttp2/issues/810

Mostly just opening this to track getting an understanding of this at some point.

**Comment by tatsuhiro-t** [comment]
I will add option to nghttp2_option to disable retaining closed streams.
Meanwhile, you can change the code so that it does not take this branch (https://github.com/nghttp2/nghttp2/blob/001d45efad9c09aadd1a18f23592633a4bd6751a/lib/nghttp2_session.c#L1189) , and observe how much memory you can save.

**Comment by tatsuhiro-t** [comment]
Sorry, the above comment is intended to nghttp2 issue, but it seems it can fit here nicely..

**Comment by mattklein123** [comment]
@tatsuhiro-t I just smoke tested your patch and in some of our use cases it will lead to 8x or more memory decrease. 💯 

Looking forward to seeing 1.2.0 come out so we can ship this more widely.
