### ISSUE TITLE
Add a flag to test configuration file

### ISSUE THREAD

**Issue by kyessenov** [lyft/envoy#499]
I think it would be useful to add a flag to test validity of the configuration JSON file.
Something similar to "-t" flag in nginx.

**Comment by mattklein123** [comment]
@kyessenov this seems useful. Right now, we use mocks to verify configurations in the test code:
https://github.com/lyft/envoy/blob/master/test/example_configs_test.cc

We do not want to depend on gmock in the prod code. Will need to figure out how to do a verification pass without using mocks which might involve some targeted changes throughout various portions of the code.

**Comment by mattklein123** [comment]
@rlazarus is taking this one.

**Comment by tschroed** [comment]
Related: https://github.com/lyft/envoy/issues/538

**Comment by mattklein123** [comment]
FYI, we need something like this pretty soon for our internal tooling. @rlazarus where are you on this? Can @junr03 help out? Another short term option is to just build a separate binary similar to what @hennna did using the full mocks.

**Comment by kyessenov** [comment]
It would be nice to verify RDS and CDS configs as well since the base config can be fairly small and most of it is fetched dynamically.

**Comment by mattklein123** [comment]
@kyessenov +1 one we need that also. cc @junr03

**Comment by mattklein123** [comment]
Going to close this out as the initial impl is done. We can open new issues with new requests.
