### ISSUE TITLE
support gRPC to JSON proxying

### ISSUE THREAD

**Issue by jbgi** [lyft/envoy#501]
à la https://github.com/grpc-ecosystem/grpc-gateway

**Comment by mattklein123** [comment]
cc @zinuga @louiscryan

**Comment by kyessenov** [comment]
@lizan

**Comment by mattklein123** [comment]
@zinuga @louiscryan @lizan FWIW, we would love to use this at Lyft also, so if there is any chance of getting this resourced at some point that would be pretty awesome.

**Comment by mattklein123** [comment]
cc @twoism @rodaine

**Comment by twoism** [comment]
I think this makes total sense to include. Let's talk about it when I'm in Seattle.

**Comment by lizan** [comment]
@mattklein123 Is there anyone already working on this at Lyft? If no, assign this to me, I'm working on bringing our [transcoding](https://github.com/istio/proxy/tree/master/contrib/endpoints/src/grpc/transcoding) to Envoy.

**Comment by mattklein123** [comment]
@lizan Yay. No, one is working on this. All yours. I will add you as read contributor so that I can assign you.

**Comment by mwitkow** [comment]
@lizan out of sheer curiosity: how do you transcode Protobuf field identifiers into JSON field names without the Envoy needing to know the `descriptor.proto` of the relevant protocol?

We had a similar problemwith our gRPC endpoints, as our proxy needed to be rebuilt whenever the schema changed, and we went with using gRPC-Web:
https://github.com/improbable-eng/grpc-web

**Comment by lizan** [comment]
It will need the protobuf descriptors to be loaded in Envoy, the proxy doesn't have to be rebuilt, but need to be reconfigured when schema change.

You can take a look at current implementation and try out it from https://github.com/istio/proxy/tree/master/src/envoy/transcoding . I'm writing docs then will make a PR in envoy. I'll be OOO next week, so it will be here the week after next.

**Comment by fengli79** [comment]
@lizan , you can use the reflection service to get the metadata from grpc backend.
https://github.com/grpc/grpc/blob/master/src/proto/grpc/reflection/v1alpha/reflection.proto

**Comment by lizan** [comment]
@fengli79 That's in our future plan and not implemented yet.

**Comment by jbgi** [comment]
@lizan, @fengli79 what about swagger documentation, does the reflection API allows to retrieve the proto file comments that are used for generating the swagger doc?

**Comment by mattklein123** [comment]
@jbgi we have a general requirement for dealing with how to auto generate REST API documentation from proto for the new v2 envoy APIs. We are going to have a solution for this one way or the other. I've been on vacation for a while, not sure if there are any updated details. cc @htuch
