### ISSUE TITLE
Envoy self health check endpoint

### ISSUE THREAD

**Issue by kuroneko25** [lyft/envoy#505]
We are thinking about putting envoy behind a Google load balancer as the front proxy layer for our service cluster. GLB (Google load balancer) requires a HTTP health check endpoint and I haven't found a way in envoy to configure a path that just returns a 200 without hitting any real backend service. This check is essentially saying that the envoy proxy layer is up and running and the frontend load balancer can route traffic to it. Any ideas?

**Comment by RomanDzhabarov** [comment]
You need to setup healthcheck filter on http connection manager with pass_through_mode: false
```
{
                "type": "both",
                "name": "health_check",
                "config": {
                  "pass_through_mode": false,
                  "endpoint": "/healthcheck"
                }
              },
```
https://lyft.github.io/envoy/docs/intro/arch_overview/health_checking.html?highlight=pass%20through#http-health-checking-filter

**Comment by RomanDzhabarov** [comment]
reach out to https://gitter.im/lyft/envoy if there are any questions/issues. Closing this issue for now.
