### ISSUE TITLE
router: support wildcard matches

### ISSUE THREAD

**Issue by tschroed** [lyft/envoy#519]
It should be possible to match *.foo.com and *-suffix.foo.com.

**Comment by mattklein123** [comment]
+1, have had a lot of requests for this.

**Comment by tschroed** [comment]
TBD: Is this a greedy match or a fall-through match?

E.g. *.foo.com would conflict with bar.foo.com in the greedy case but in the fall-through, a specific bar.foo.com rule would take precedence and *.foo.com would match baz.foo.com (assuming no more specific match).

**Comment by tschroed** [comment]
I've got this one in the oven.
