### ISSUE TITLE
Support adding/overwriting request headers before forwarding request

### ISSUE THREAD

**Issue by rshriram** [lyft/envoy#539]
It would be useful to support addition of "request" headers on per-route or per-virtual host basis for use cases like forwarding a request to auth backends, etc.
( @mattklein123  please assign this to me).

**Comment by kyessenov** [comment]
Is this for proxy-to-proxy communication? In Istio, we need to insert pod identity into the source request to enforce source-destination policies on the server side. We've been using a custom filter to do that, but since values are not dynamic, native Envoy support would be great.

**Comment by mattklein123** [comment]
Please reconcile with "global" response headers to add/remove here: https://lyft.github.io/envoy/docs/configuration/http_conn_man/route_config/route_config.html

We might want to move this into both virtual host and route level, etc. Needs some thinking. Please propose configuration schema.

**Comment by rshriram** [comment]
I was thinking more from the standard LDAP/IAM auth stuff. Request comes in, you add a bunch of headers to it, forward to IAM, get authenticated, and then you strip them off and redirect to original destination. But, the istio case applies equally well here.

**Comment by mattklein123** [comment]
fixed by https://github.com/lyft/envoy/pull/630
