### ISSUE TITLE
How to support TLS passthrough

### ISSUE THREAD

**Issue by asambeka** [lyft/envoy#565]
I am trying to find equivalent of HAProxy [TLS Pass-through](https://www.haproxy.com/doc/aloha/7.0/deployment_guides/tls_layouts.html#ssl-tls-passthrough) in Envoy. Basically I want to ensure TLS termination happens on workloads and at the same time having the ability to restrict connections based on SSL/TLS version and support for SNI. Is this supported natively? How can I enable the functionality.

**Comment by mattklein123** [comment]
Envoy supports pass through via tcp_proxy filter (without TLS listener and/or TLS upstream), or bridging (via TLS listener and/or TLS upstream). If I understand correctly, haproxy also supports a form of pass-through where it sniffs the handshake and does routing based on handshake params. Envoy does not support this currently.

**Comment by asambeka** [comment]
Thanks, any plan/roadmap to implement handshake support? Also, do you have any example of tcp_proxy for TLS pass-through?

Thanks

**Comment by mattklein123** [comment]
There is no current plan to implement handshake sniffing/routing without de/re-encryption. Feel free to open a GH issue to track the request.

[Here](https://github.com/lyft/envoy/blob/master/configs/envoy_service_to_service.template.json#L244) is an example of using tcp_proxy also with mongo and ratelimit filters, but you can just use tcp_proxy to proxy a byte stream if you wish. The fact that the underlying stream is TLS is not relevant.
