### ISSUE TITLE
Json Schema: Add tests for JSON Schemas

### ISSUE THREAD

**Issue by ccaraman** [lyft/envoy#572]
Currently, there are no explicit tests for JSON schemas. There are a few places in the code path that test for some invalid values, but it doesn't cover all schemas. 

Potential solution: https://github.com/json-schema-org/JSON-Schema-Test-Suite

**Comment by mattklein123** [comment]
Testing facility added in https://github.com/lyft/envoy/pull/715. Thanks @danielhochman !
