### ISSUE TITLE
Document limits on cluster names and reject cluster names that exceed it

### ISSUE THREAD

**Issue by kyessenov** [lyft/envoy#573]
Currently, Envoy fails catastrophically for a CDS response that seems to send a long cluster name.
https://gist.github.com/kyessenov/988c7aac2df8fb87f398ae64a77bf3e3
It's unclear to me what the limit is. Also, I don't think a hard crash is appropriate here.

**Comment by mattklein123** [comment]
Note, this won't hard crash on a release build (please verify), but we can/will do better here.

**Comment by kyessenov** [comment]
Correct, only happens in debug build. It's making debugging our custom filter harder since I can't get past CDS response.

**Comment by mattklein123** [comment]
Yes, we will fix. The limit comes from here: https://github.com/lyft/envoy/blob/master/source/common/stats/stats_impl.h#L19, but this includes the prefix, and the trailing stats, so I'm not exactly sure what the max cluster name size is. We will have to pick something reasonable. Do you have a plan for truncating?

**Comment by kyessenov** [comment]
I create cluster names from service hostnames, ports, and tags, so it's a fairly long string.
I'm ok creating a compression/encoding scheme since I also control RDS and can just rename all clusters to fit within the limits. Is there an inherent reason to keep cluster names short? Can we just automatically truncate for stats and allow longer cluster names?

**Comment by mattklein123** [comment]
We do auto truncate for stats which is why it doesn't crash on a release build. I guess we could remove the ASSERT, but it's there for a reason since ultimately the generated stats will make no sense.

**Comment by mattklein123** [comment]
@junr03 can you take a look at this next week.
