### ISSUE TITLE
Port server support for tests that bind to ports

### ISSUE THREAD

**Issue by htuch** [lyft/envoy#574]
Certain test environments (e.g. @Google) don't support tests that have fixed port binding. In general, it would be helpful to get port allocations from a port server (and use some arbitrary unbound port when not available). This is provided by https://github.com/google/python_portpicker. This issue tracks figuring out what makes sense for Envoy tests in this respect and implementing it.

**Comment by htuch** [comment]
avd also brought up that a bind/list to port 0 is an equally valid solution (and probably simpler) solution for single process tests - the clients can easily learn of the actual port via shared memory.

**Comment by jamessynge** [comment]
You can assign this to me, I've got it pretty much implemented along the lines that avd suggested with port 0.

**Comment by htuch** [comment]
You can reassign to me, I'm going to get all the tests moved over to this, since it's required to avoid having `bazel test //test/...` flake. Bazel runs individual test targets in parallel.

**Comment by mattklein123** [comment]
I think we have what we need here per @htuch so closing this out.
