### ISSUE TITLE
Bind listener to multiple addresses instead of one

### ISSUE THREAD

**Issue by wattli** [lyft/envoy#595]
Currently a listener is bound to one address ([link](https://lyft.github.io/envoy/docs/configuration/listeners/listeners.html)), it would be great to allow one listener bound to multiple addresses.

**Comment by mattklein123** [comment]
We are working on the v2 API now. This can be implemented by either multiple listeners or the new matching rules for filter stacks we are designing. Closing this out as won't fix. cc @htuch
