### ISSUE TITLE
Add profiler path to configuration

### ISSUE THREAD

**Issue by htuch** [lyft/envoy#596]
@hennna discovered that during integration tests, we're not actually starting the profiler in https://github.com/lyft/envoy/blob/master/test/integration/integration_admin_test.cc#L108. This then means we never exercise some of the profiler disable code in https://github.com/lyft/envoy/blob/master/test/integration/integration_admin_test.cc#L113.

The root cause is the hardcoded path (https://github.com/lyft/envoy/blob/master/source/server/http/admin.cc#L166) of the profiler doesn't play well in the test environment.

There are two issues here that should probably be fixed:

1. The path should be configurable via the Envoy config JSON.

2. (As suggested by @hennna) we should pass back the success of the CPU profiler start to the caller (and eventually the HTTP request).

@mattklein123 for thoughts on this, @hennna for issue assignment.

**Comment by mattklein123** [comment]
+1, sure sounds good to me.

**Comment by mattklein123** [comment]
Fixed by @hennna
