### ISSUE TITLE
Switch from tclap to gflags

### ISSUE THREAD

**Issue by htuch** [lyft/envoy#613]
We've previously discussed switching the flags handling to gflags (https://github.com/gflags/gflags), this issue will track work on moving forward with this.

**Comment by mattklein123** [comment]
I don't really care about this one way or the other, but can I ask what the difference is? It seems like change for change sake? Do you have internal hooks for gflags that do something special?

**Comment by htuch** [comment]
We have a lot of production tooling and libraries that knows how to work with the gflags format, so from our side it would make handling Envoy more uniform. We could try and support both if you feel this would be helpful but we'll just do gflags if it's a potato potatah thing.

**Comment by mattklein123** [comment]
Nope don't care. That's fine.

**Comment by htuch** [comment]
@rlazarus is interested in taking a look.

**Comment by rlazarus** [comment]
I don't want to try to add a dependency while @htuch is rejiggering the build (#415), so barring any objections I'll wait until he's finished before committing anything here.

From playing around in the meantime, some notes on compatibility:

- tclap uses hyphens in flag names `--like-this` while gflags uses underscores `--like_this`. (It isn't just a matter of idiom: in gflags, the flag name is the same as the C++ identifier, so hyphens aren't legal.) Obviously we can't break every existing user by renaming all the flags to use underscores, so I propose the slightly-ugly workaround of running the argv through a find-replace for each flag name (e.g. replace `"--config-path"` with `"--config_path"`) before passing to gflags for parsing. That'll support both forms.

- gflags doesn't offer single-letter aliases (e.g. `-c` being equivalent to `--config-path`) but I propose to emulate that behavior by adding both as flags, using whichever one is set, and crashing if they're both set. (It also doesn't support combining single-letter flags like `rm -rf` but Envoy only has one boolean flag, so we don't care.)

- Flag values in gflags can be globally accessible -- for example if we put `DECLARE_uint32(concurrency);` in a header file, then anywhere else we can use the uint32 variable `FLAGS_concurrency`. That means, if we wanted to, we could do away with Envoy's `Options` type. I propose to ignore this, and keep all the gflags business wrapped up in options_impl.cc, the same way all the tclap business is now. If we ever decide we want to change that, we can do it as a separate refactor.

Note that with the proposed tweaks above, we should be able to do this backwards-compatibly -- which means we don't necessarily need to block the freeze for #625.

Other details are the same: `--help` will still print a (different) auto-generated usage string, `--` will still stop parsing flags, and so on. The [howto](https://gflags.github.io/gflags/) has all the details, both user-facing and dev-facing.

**Comment by htuch** [comment]
How are you planning to munge the auto generated --help to reflect the
hacks to the flags in points one and two?

On Mon, Mar 27, 2017 at 6:45 PM Reuven Lazarus <notifications@github.com>
wrote:

I don't want to try to add a dependency while @htuch
<https://github.com/htuch> is rejiggering the build (#415
<https://github.com/lyft/envoy/issues/415>), so barring any objections I'll
wait until he's finished before committing anything here.

From playing around in the meantime, some notes on compatibility:

   -

   tclap uses hyphens in flag names --like-this while gflags uses
   underscores --like_this. (It isn't just a matter of idiom: in gflags,
   the flag name is the same as the C++ identifier, so hyphens aren't legal.)
   Obviously we can't break every existing user by renaming all the flags to
   use underscores, so I propose the slightly-ugly workaround of running the
   argv through a find-replace for each flag name (e.g. replace
   "--config-path" with "--config_path") before passing to gflags for
   parsing. That'll support both forms.
   -

   gflags doesn't offer single-letter aliases (e.g. -c being equivalent to
   --config-path) but I propose to emulate that behavior by adding both as
   flags, using whichever one is set, and crashing if they're both set. (It
   also doesn't support combining single-letter flags like rm -rf but Envoy
   only has one boolean flag, so we don't care.)
   -

   Flag values in gflags can be globally accessible -- for example if we
   put DECLARE_uint32(concurrency); in a header file, then anywhere else we
   can use the uint32 variable FLAGS_concurrency. That means, if we wanted
   to, we could do away with Envoy's Options type. I propose to ignore
   this, and keep all the gflags business wrapped up in options_impl.cc, the
   same way all the tclap business is now. If we ever decide we want to change
   that, we can do it as a separate refactor.

Note that with the proposed tweaks above, we should be able to do this
backwards-compatibly -- which means we don't necessarily need to block the
freeze for #625 <https://github.com/lyft/envoy/issues/625>.

Other details are the same: --help will still print a (different)
auto-generated usage string, -- will still stop parsing flags, and so on.
The howto <https://gflags.github.io/gflags/> has all the details, both
user-facing and dev-facing.

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/lyft/envoy/issues/613#issuecomment-289608385>, or mute
the thread

**Comment by rlazarus** [comment]
Nothing fancy. The underscored name becomes the "canonical form" for Envoy flags, so that's what will be listed in `--help`. (I don't propose trying to avoid that; as long as we're switching to gflags, the underscores will inevitably leak out in other ways too.) We can include a note in the usage string about how hyphens are accepted too, and that'll display at the top of `--help`. For consistency we should also update flag names as mentioned in the docs.

For the single-letter aliases, we can just have `-c`'s help string be "Alias for --config_path" -- no need to try to merge the entries.

**Comment by htuch** [comment]
SGTM. I agree on waiting for the Bazel stuff, we'll need to get gflags in both the Docker CI image WORKSPACE and also building under Bazel for developer-local builds via `repositories.bzl`. You might want to double check with @mattklein123 if the backwards compatibility is required.

**Comment by mattklein123** [comment]
I would prefer that we maintain backwards compatibility even if only on a temporary hack basis until we get everything at Lyft upgraded.

**Comment by mattklein123** [comment]
@rlazarus can we sync up on this tomorrow? @htuch mentioned that you all might not need this anymore? I would like to close as won't fix or do the switch by the end of next week if possible. I'm trying to close out all the major churn so we can ship 1.3.0 in a couple of weeks.

**Comment by mattklein123** [comment]
Going to close this for now. Let's reopen if this is still needed at some point.
