### ISSUE TITLE
Require peer certificate when `ca_cert_file` is specified in ssl_context

### ISSUE THREAD

**Issue by lookuptable** [lyft/envoy#615]
Currently when the `ca_cert_file` is specified without `verify_subject_alt_name` or `verify_certificate_hash` in `ssl_context`, the SSL connection can still be successfully established when the peer does NOT present a certificate. This behavior may not be desirable as a peer without a valid cert and a peer with valid cert are treated equally and both can successfully establish a connection.

We should change it such that a peer must present a verifiable cert when ca_cert_file is set. With this change, the following cases can be supported:
- No `ca_cert_file`: allow any peer
- Only set `ca_cert_file`: allow peers with valid certs
- `ca_cert_file` and `verify_certificate_hash`: allow peers with valid certs of a particular hash
- `ca_cert_file` and `verify_subject_alt_name`: allow peers with valid certs and the SAN must match

**Comment by lookuptable** [comment]
@mattklein123 can you please assign this issue to me?

**Comment by mattklein123** [comment]
@lookuptable have at it, and please sign CLA when you get a chance.

**Comment by lookuptable** [comment]
I have signed CLA when submitting a PR here last time :)

**Comment by PiotrSikora** [comment]
@mattklein123 could you re-open this, since the change was reverted in #668?

**Comment by PiotrSikora** [comment]
@mattklein123 can you re-assign this to me? Thanks!

**Comment by timperrett** [comment]
@PiotrSikora just looking into this and was looking for a bit of clarification about the following use cases:

* 1-way SSL with an externally rooted CA: satisfied by the use of `cert_chain_file` and `private_key_file`
* 1-way SSL with a privately rooted CA: satisfied by the use of `cert_chain_file` and `private_key_file`, but the client will have to trust the private CA (this is normal and fine)
* 2-way SSL with a privately rooted CA: currently requires the setting of either `verify_certificate_hash` **OR** `verify_subject_alt_name` to force client verification, along with `ca_cert_file` to have a set of CAs to verify the inbound peer against.

Is this an accurate assessment? If so, it looks like a fix was put in place already, but reverted already; I would like to only have to specify the `ca_cert_file` to enable checking of inbound peer certificates, as specifying `verify_certificate_hash` / `verify_subject_alt_name` does not make sense in my use case.

**Comment by mattklein123** [comment]
@PiotrSikora @myidpt  are either of you still planning on doing this? Would love to get this closed out as it's only a revert of the revert and adding a config option. If you don't have time that's fine, but please let me know and we can find someone else to take care of it.

**Comment by PiotrSikora** [comment]
@mattklein123 I'm going to do it this week. Got sidetracked, sorry!

**Comment by mattklein123** [comment]
@PiotrSikora awesome thanks and np.

**Comment by mattklein123** [comment]
@PiotrSikora @myidpt @wattli Can one of you do this issue this week? Otherwise I'm just going to take care of it as it's trivial and I would like to close it out.

**Comment by timperrett** [comment]
@mattklein123 if you do get to this, just a big of feedback: have been running #648 for a while now, and whilst it does seem to work well for the most part, we see this strange error when using cURL:

```
* GnuTLS recv error (-110): The TLS connection was non-properly terminated.
* Closing connection 0
curl: (56) GnuTLS recv error (-110): The TLS connection was non-properly terminated.
```

Whilst i'm ok accepting this is just curl being garbage, `httpie` also runs into issues. libcurl on the other hand seems ok with it. I'm going to try and reduce this into a concrete case as I have a few variables right now, but if you're in that code it might be good to keep an eye out to see if there's anything obviously wrong that would cause this kind of improper termination. 

Cheers

**Comment by mattklein123** [comment]
@timperrett a little suspicious this change is related to a connection termination issue. Is this in the case where a user does not supply a cert and the connection is closed?

**Comment by timperrett** [comment]
@mattklein123 nope, this happens when i supply a cert and a key :-) The cert and key should be valid for the request (note it doesn't matter if i try to verify the remote or not in this case), so its a little strange. I dont mean to hijack this thread; if there's something you'd like to help try and isolate the issue or if its not related to this im happy to do that and file another issue.

**Comment by mattklein123** [comment]
@timperrett yeah might be best to try to isolate the problem and open a new issue.

**Comment by lookuptable** [comment]
@mattklein123 I can work on this this week if you re-assign it to me. 

Sorry for taking so long on this. I've been on vacation and did not check notifications as often as I used to.

**Comment by mattklein123** [comment]
Thanks @lookuptable

**Comment by PiotrSikora** [comment]
@mattklein123 @lookuptable I'll finish this today, I've been sitting for the patch for a while, but I need to revamp tests, since the tests from #648 didn't verify anything.

**Comment by PiotrSikora** [comment]
@timperrett I expect the issue you see is because Envoy doesn't set client CA list, so no "accepted CAs" list is sent during the handshake. From your description, it sounds like client certificates works without client CA list with OpenSSL, but not with GnuTLS.

I'll try to verify and fix this later today.

**Comment by timperrett** [comment]
@PiotrSikora as you were posting this i just verified the issue. I'm supplying a CA PEM that contains multiple certificates (as there are multiple valid callers in this case) and it appears envoy is only picking the first cert of the file, not the list as you suspected. 

Hope this helps!

**Comment by PiotrSikora** [comment]
@timperrett Do you have config, certificates & keys that you could share to replicate the issue you're seeing? I'm having hard time replicating it with multiple CAs, even after building cURL with GnuTLS:

    $ curl --version
    curl 7.54.1 (x86_64-apple-darwin16.6.0) libcurl/7.54.1 GnuTLS/3.5.14 zlib/1.2.11
    Release-Date: 2017-06-14
    Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
    Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy 

For the record, I'm getting the same error as you _when I don't provide required client certificate_, i.e.:

- with #648:

      * GnuTLS recv error (-110): The TLS connection was non-properly terminated.
      * Closing connection 0
      curl: (56) GnuTLS recv error (-110): The TLS connection was non-properly terminated.

- with #1203:

      * gnutls_handshake() failed: Handshake failed
      * Closing connection 0
      curl: (35) gnutls_handshake() failed: Handshake failed

But I always get successful connection, regardless of the order of CAs in `ca_cert_file` (so it's not like Envoy is picking only the first CA that happens to work), when I provide client certificate.

**Comment by PiotrSikora** [comment]
Also, just to confirm... you're still linking Envoy against BoringSSL, right?

**Comment by timperrett** [comment]
@PiotrSikora thats essentially correct, yes. I'm constructing a simplistic test using the same cert on the client and server side (with a cert+chain combined into a single pem). The certificates are not issued as leaves from the root CA, they have an intermediate CA (`root -> ICA -> leaf cert`) and leaves are issued from the intermediate.

Now im running the patch in #1203 with one change:

```
    verify_mode = SSL_VERIFY_PEER;
// changed too:
    verify_mode = SSL_VERIFY_PEER | SSL_VERIFY_FAIL_IF_NO_PEER_CERT;
```

As in this case I want everything to use mTLS if a `ca_cert_file` was specified (understand you're working on a better, more configurable fix, but this gets me there today with more constraints that are acceptable to me right now).

I'm using the following curl + openssl:

```
$ curl --version
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets

$ openssl version
OpenSSL 1.0.2g  1 Mar 2016
```

Two scenarios here:

**Scenario A**

cert and key are same on both client and server. The cacert PEM contains multiple trusted CAs, in no particular order (note the first cert is NOT the root or intermediate for the client cert being supplied). If I supply no certificate, key or cacert when calling Envoy, then i get:

```
curl -vG https://127.0.0.1:4466
* Rebuilt URL to: https://127.0.0.1:4466/
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 4466 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 692 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* gnutls_handshake() failed: Error in the push function.
* Closing connection 0
curl: (35) gnutls_handshake() failed: Error in the push function.
```

If I *do* supply a cert, key and cacert (in this case, the same as being used on the server side) then I get:

```
$ curl -k -vG --cert etc/certs/cert_chain.pem --key etc/certs/key.pem --cacert etc/certs/ca.pem https://127.0.0.1:4466
* Rebuilt URL to: https://127.0.0.1:4466/
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 4466 (#0)
* found 14 certificates in etc/certs/ca.pem
* found 692 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* gnutls_handshake() failed: Handshake failed
* Closing connection 0
curl: (35) gnutls_handshake() failed: Handshake failed
```

Oddly, in this configuration `openssl s_client` CAN connect using the same test certs on the client. 

**Scenario B**

cert and key are same on both client and server. The cacert PEM contains multiple trusted CAs, with the CA root or one of the intermediates for the calling client cert **at the top of the file**. If I supply no certificate, key or cacert when calling Envoy, then the response is the same as in scenario A. However, in the event I supply a valid cert and key, the request goes through perfectly (as shown below in my local Envoy test harness):

```
$ curl -k -vG --cert etc/certs/cert_with_chain.pem --key etc/certs/key.pem --cacert etc/certs/ca.pem https://127.0.0.1:4466
* Rebuilt URL to: https://127.0.0.1:4466/
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 4466 (#0)
* found 1 certificates in etc/certs/ca.pem
* found 692 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification SKIPPED
* 	 server certificate status verification SKIPPED
* 	 common name: REDACTED
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: CN=REDACTED
* 	 start date: Tue, 27 Jun 2017 16:03:36 GMT
* 	 expire date: Wed, 27 Jun 2018 16:04:06 GMT
* 	 issuer: REDACTED
* 	 compression: NULL
* ALPN, server did not agree to a protocol
> GET / HTTP/1.1
> Host: 127.0.0.1:4466
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 200 OK
< date: Thu, 06 Jul 2017 06:40:47 GMT
< content-length: 14
< content-type: text/plain; charset=utf-8
< x-envoy-upstream-service-time: 2
< server: envoy
<
Aloha v1.0.79
* Connection #0 to host 127.0.0.1 left intact
```

Does this help? Sadly i'm not able to supply the certificate material. If you have any questions about the certs or the test scenarios, then I can happily answer them for you.

**Comment by timperrett** [comment]
Oh, and yep, this is a vanilla Envoy build - we're not changing any of the linking or otherwise. We have a few small patches, but its mainly to the build infra, and not the source.

**Comment by PiotrSikora** [comment]
Sigh, it took me a few minutes to fix the issue (since it was the list, like I assumed earlier) and whole day to realize that `openssl s_client` doesn't sent intermediates from file specified by `-cert`.

Anyway, moving this into #1220, since it's clearly a different issue.
