### ISSUE TITLE
config: create config breaking change policy

### ISSUE THREAD

**Issue by mattklein123** [lyft/envoy#625]
We need to lock down the config, having a breaking change policy around supporting old/new, deprecation period, then deleting old, as well as explicit notification of breaking changes in release notes.

@rshriram we can use this to possibly do any last minute "nice to haves" before we lock it down.

**Comment by htuch** [comment]
We could maybe squeeze in #613 before the freeze as well, to provide additional user stability at that date.

**Comment by mattklein123** [comment]
@htuch sure let's do the gflags conversion. Can you find someone to take that ticket?

**Comment by htuch** [comment]
@mattklein123 Yeah, is there an approximate date for the freeze yet?

**Comment by mattklein123** [comment]
No, no specific date. We can discuss what makes sense. However, I think we need to do it sooner rather than later given the number of companies that are evaluating and probably moving towards production.

**Comment by RomanDzhabarov** [comment]
not so much a blocker, but for tracing (lightstep) we'd need to move `access_token` param from the driver configuration into `config` part of the driver. (https://lyft.github.io/envoy/docs/configuration/overview/tracing.html?highlight=tracing#lightstep-driver)

**Comment by rshriram** [comment]
Wishlist:

circuit_breakers -> bulkheads
outlier_detection -> circuit_breakers
In virtual_hosts/route:
 prefix -> prefix_match (goes nicely with prefix_rewrite)
 path -> path_match
 headers -> headers_match

**Comment by mattklein123** [comment]
> circuit_breakers -> bulkheads
outlier_detection -> circuit_breakers

This is terminology that is not consistent across the industry and will never find agreement. So IMO there is no point changing this as someone will complain about the changed definitions.

> prefix -> prefix_match (goes nicely with prefix_rewrite)
path -> path_match
headers -> headers_match

No objections from me.

**Comment by mattklein123** [comment]
@htuch let's use this issue to track a general refresh of the contribution guidelines. We can discuss offline and then do a proposal here.
