### ISSUE TITLE
Restore socket passing validation in hot restart tests

### ISSUE THREAD

**Issue by htuch** [lyft/envoy#654]
#650 broke this aspect of the integration test, since the JSON config now specifies port 0 for all listeners. We can add a command line flag to print out the config JSON with port 0 addresses replaced with the actual ports the listeners/admin are bound to post-initialization, this should allow the test to continue to work as expected.

**Comment by htuch** [comment]
Another suggestion from @mattklein123: have the admin endpoint be capable of emitting the listener JSON with bound ports. We would still need CLI flag support for discovering the admin endpoint address if it is configured to bind to port 0.

**Comment by htuch** [comment]
@hennna

**Comment by htuch** [comment]
We will structure this as a Bazel `sh_test` (https://bazel.build/versions/master/docs/be/shell.html), so there should be no issue with shared memory as mentioned in #650.

**Comment by htuch** [comment]
> I don't see how the flag would work unless it somehow talked to the existing process over RPC.

Here's a suggested flow. When the Envoy process starts with the `--admin_address_file` flag, it writes the admin address, e.g. `http://1.2.3.4:5` to a given file. In the wrapping script, we then query this with curl to find the listener JSON and use that to assembler the config to feed into the second Envoy process.

**Comment by mattklein123** [comment]
Yeah, I had the same thought about writing it to a file (kind of like PID file). SGTM.

**Comment by hennna** [comment]
I can take this one.
