### ISSUE TITLE
Optional's can't be used with move only types.

### ISSUE THREAD

**Issue by voldyman** [lyft/envoy#66]
The [Optional](https://github.com/lyft/envoy/blob/master/include/envoy/common/optional.h) implementation doesn't handle r-value references and hence can't be used with move-only types, like std::unique_ptr.

Adding a move constructor solves this problem, http://ideone.com/PpByK5

*sidenote*: the rule of 5 might be applicable http://en.cppreference.com/w/cpp/language/rule_of_three

**Comment by mattklein123** [comment]
Thanks for your comment. In general we prefer to not add code until it is needed so we can add this constructor if/when we need to use it in the future.
