### ISSUE TITLE
Does Envoy support TCP proxy?

### ISSUE THREAD

**Issue by abadiaharon** [lyft/envoy#684]
Hello can you please let me know if Envoy support TCP proxy? I saw that external clients can connect to the “Front” Envoy Edge Proxy using HTTP,TLS. Can you please let me know if there is any possibility for external clients to connect using TCP connection? Some kind of HAProxy replacement. For example:

Request tcp ip:port
                0.0.0.0:7000            
Forwarded  tcp ip:port
               192.168.1.11:8000

Thanks
Aharon

**Comment by mattklein123** [comment]
Yes, Envoy supports TCP proxy. Overview with links to config details here: https://lyft.github.io/envoy/docs/intro/arch_overview/tcp_proxy.html
