### ISSUE TITLE
ContextImplTest fails if it has been more than one day since last clean build

### ISSUE THREAD

**Issue by dnoe** [lyft/envoy#704]
The ContextImplTest failed for me this afternoon:

test/common/ssl/context_impl_test.cc:93: Failure
Value of: 15 == context->daysUntilFirstCertExpires() || 14 == context->daysUntilFirstCertExpires()
 Actual: false
Expected: true

It has been about a day since I last did a bazel clean, so it appears the problem is that the SSL certs are no longer expiring in the expected timeframe.  I will fix this issue properly within the next few days.  In the meantime, if you encounter this issue, just run "bazel clean" which will force regeneration of the SSL certs.

**Comment by htuch** [comment]
This tests could use a `setup_cmds` to run a script for a custom cert that gets regenerated each time. I don't want to rebuild all certs, since we should not trigger other tests to rerun.

**Comment by mattklein123** [comment]
fixed by https://github.com/lyft/envoy/pull/723
