### ISSUE TITLE
hot restart: a config error in the child causes the parent to never initialize

### ISSUE THREAD

**Issue by kyessenov** [lyft/envoy#726]
From gitter:
it seems that when a child envoy has a broken config, the parent initialization does not complete. That is if epoch 1 starts and then quits due to config error, epoch 0 remains in initialization phase, and no future restart is possible. Here is a sample log https://gist.github.com/kyessenov/04e8dca3f5b176683fa219d3dca27cf3

**Comment by mattklein123** [comment]
Per offline discussion closing as won't fix for now. (See PR for more info).
