### ISSUE TITLE
ssl: poll boringssl in ci to see of chromium-stable has changed

### ISSUE THREAD

**Issue by mattklein123** [lyft/envoy#761]
There is no notification, so let's figure out a way to get notified if the SHA has changed.

**Comment by PiotrSikora** [comment]
Why do we single out BoringSSL here? There are other important dependencies that are not updated (i.e. nghttp2).

**Comment by mattklein123** [comment]
> Why do we single out BoringSSL here? There are other important dependencies that are not updated (i.e. nghttp2).

Mostly because of the security implications of not being up to date. We should probably figure out a notification system for all dependencies.

**Comment by moderation** [comment]
You can get a programmatic notification of a nghttp2 release at https://github.com/nghttp2/nghttp2/releases.atom. Where ideally would these notifications get sent to @mattklein123 ? Gitter, mailing list, RSS etc.?

**Comment by mattklein123** [comment]
Optimally mailing list. Just need to find some time to get someone to set something up. We could do something in CI, write an AWS lambda, etc.

**Comment by mattklein123** [comment]
Google is now generally managing our use of boringssl so going to close this out.
