### ISSUE TITLE
Figure out the right way to handle stack unwinding with gperftools

### ISSUE THREAD

**Issue by htuch** [lyft/envoy#834]
Today we use frame pointers, which don't extend into the underlying C/C++ libraries (libc, libgcc, libstdc++), so we probably lose some performance visibility. We could improve visibility by using libunwind and the appropriate  https://github.com/gperftools/gperftools/wiki/gperftools'-stacktrace-capturing-methods-and-their-issues. This comes at some performance hit and we'd need to verify it works well with all our libraries and static link story.

If we stick with frame pointers, we should use `--disable-libunwind` to avoid the hack in https://github.com/lyft/envoy/pull/824.

@dnoe as he has been looking at backtrace stuff recently in https://github.com/lyft/envoy/pull/833.

**Comment by htuch** [comment]
@alk

**Comment by htuch** [comment]
@qiwzhang experienced an issue during the external dep build where the `gperftools` dep was also failing due to a local install of `libunwind8`. I'm not sure why it breaks with `gperftools` 2.5, but if we go down the route of `--disable-libunwind`, we might avoid this problem for other developers.

**Comment by mattklein123** [comment]
@htuch @dnoe I feel like we are kind of done with this issue since we fixed dependencies to have frame pointers. It's not perfect, but to me it's good enough. Should we keep this open? Or do we need to do the ```disable-libunwind``` thing above?

**Comment by alk** [comment]
So I've fixed libunwind detection in gperftools 2.6 release candidate. But my advise would be to link with libunwind especially if you actually plan to use cpu profiler, debug allocator etc. Apparently libunwind is not abandoned and isn't that slow and has very decent chance of working in all cases.

**Comment by mattklein123** [comment]
Closing this for now via https://github.com/lyft/envoy/pull/1077. If frame pointer unwind becomes an issue for some reason in the future we can revisit.
