### ISSUE TITLE
Accessing Source IP Address in HTTP Filter

### ISSUE THREAD

**Issue by sushilks** [lyft/envoy#862]
Hi, 
   I was looking to access the Source IP address for the stream in the HTTP filter implementation, possibly in the decodeHeaders(..) callback. 
What is the best way to get access to this information ?
Thanks and any help is much appreciated,
-SK

**Comment by mattklein123** [comment]
https://github.com/lyft/envoy/blob/master/include/envoy/http/filter.h#L123

**Comment by sushilks** [comment]
Thanks for your quick response @mattklein123, 
I verified the function you pointed to in filter.h, This function " downstreamAddress()" returns the destination address for the packet. 
However I am looking to find the source address of the packet which is the address of the client that initiated the connection. 
Can you point to the function that has the source address information.

**Comment by mattklein123** [comment]
downstreamAddress() is the source address.

**Comment by sushilks** [comment]
Got it, Thanks
I guess I got confused on the integration testing as I was expecting the ip address to be 127.0.0.1, but the integration test was showing 10.0.0.1 which was hardcoded into the test Mock object.
