### ISSUE TITLE
custom access log format won't break line

### ISSUE THREAD

**Issue by fabware** [lyft/envoy#87]
Use default access log format will result in logs without break lines. I have to attach a \n in format string.

"format": "[%START_TIME%] \"%REQ(:METHOD)%\" \"%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%\" %PROTOCOL% %RESPONSE_CODE% %FAILURE_REASON% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% \"%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%\" \"%REQ(X-FORWARDED-FOR?X-ENVOY-EXTERNAL-ADDRESS)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\""

Tested on ubuntu 14.04 with envoy 1.0.

**Comment by mattklein123** [comment]
This is a doc bug, the default format string compiled into the code does include a '\n'. We will fix the docs and make the lack of new line more clear. We don't want to assume a new line because different deployments might want different separators for some reason.

**Comment by fabware** [comment]
thanks for you clarification.

**Comment by mattklein123** [comment]
Reopening just to track doc fix

**Comment by RomanDzhabarov** [comment]
Put more details into access log docs: https://github.com/lyft/envoy/pull/93
