### ISSUE TITLE
SDS: Provide additional info in requests

### ISSUE THREAD

**Issue by bndw** [lyft/envoy#887]
As a front proxy, it would be helpful if Envoy could include additional metadata (tags) in its requests to the SDS, such as `region` and `az`.

For example, a front proxy in `az=a` should only receive upstream hosts in `az=a` from the SDS. This would likely require an update to both Envoy and the SDS API.

**Comment by mattklein123** [comment]
Will be covered in v2 API. Can potentially add v1.5 API if urgent.

**Comment by bndw** [comment]
Hi Matt, 

If this could make it in a v1.5 that would be really helpful. Are these parameters going to be passed in a query string to the SDS?

**Comment by mattklein123** [comment]
The new API is gRPC based and will have a parallel JSON version. We should have something published for initial review next week. Realistically, it will take a couple of months before this is fully implemented. I'm happy to provide guidance if someone wants to contribute a small addition to the current SDS JSON API, but I don't think we will have resources to do the work.

**Comment by bndw** [comment]
If you're referring to lyft/discovery SDS JSON API, I could likely contribute that update if you can provide the changes to the API.

**Comment by mattklein123** [comment]
@bndw I think the easiest thing to do right now is not to change the URL of the REST call, but to just add the additional info in headers when the call is made. This is not super great from a consistency perspective, but it won't be a breaking change. It will all be cleaned up in the v2 API.

https://github.com/lyft/envoy/blob/master/source/common/upstream/sds.cc#L98

Basically, when the SDS is created, pass in LocalInfo, and then add service cluster, service node, etc. as headers.

**Comment by RomanDzhabarov** [comment]
"For example, a front proxy in az=a should only receive upstream hosts in az=a from the SDS" although this is good in terms of cost/latency perspective, this will create uneven per-host load on the upstream cluster behind the front envoy (in case of imbalance of hosts per AZ)

For example, 2 front envoy hosts route to 5 upstream hosts in 2 AZs (1 host in first az, 4 hosts in second AZ), per host RPS will be 4 times higher on the host in first AZ.

For this reason we have zone aware routing, https://lyft.github.io/envoy/docs/intro/arch_overview/load_balancing.html?highlight=zone%20aware#zone-aware-routing

I'm not against adding this feature as I can see that it can potentially be used for big upstream clusters where RPS discrepancy will be negligible, but I think we should reflect potential problem in the doc

**Comment by mattklein123** [comment]
Closing per gitter chat. The v2 EDS API will cover this and is coming soon.
