### ISSUE TITLE
SSL: automatically reload SSL certificates

### ISSUE THREAD

**Issue by PiotrSikora** [lyft/envoy#891]
We should watch SSL certificates on disk and reload them (and recreate `SSL_CTX`) when they change.

It's unclear whether this is the perfect solution (vs LDS with encrypted private keys).

Needed by Istio.

cc @kyessenov @louiscryan

**Comment by louiscryan** [comment]
We also need to support the appropriate draining behaviors as certificates approach their expirations. This is true for both the client and server certificates in mTLS.

**Comment by kyessenov** [comment]
There is also some need for coordination between impending LDS and kube volume mounter. Or add some way to fetch the actual certs from the discovery service rather than expecting it to be on a local file system.

**Comment by mattklein123** [comment]
IMO it would be much better to just do this via LDS, which will natively support draining of the old listener. If we have LDS, do we need explicit support for cert reloading?

**Comment by kyessenov** [comment]
Are certs going to be inlined in the LDS response?

**Comment by PiotrSikora** [comment]
Yes, that will be one of the options (unclear if the only one, though).

**Comment by mattklein123** [comment]
> Are certs going to be inlined in the LDS response?

@htuch is working on API specification now. If we need that we should have that option. We will also obviously have the option to read from disk.

**Comment by louiscryan** [comment]
Will need to assess the security properties of key distribution vs common
best practices. Kubernetes has 'secrets' which it makes some assertions
about that we are currently leveraging in Istio when we ship certificates
as files. We'll need to have some authentication mechanism in place to be
able to rely on an API for fetching certs. Perhaps we use the filesystem as
a bootstrap for the API?

**Comment by mattklein123** [comment]
Yup will need thinking. Obviously, we will discovery LDS typically via LDS, and could do mTLS to config servers via on disk cert.

**Comment by mattklein123** [comment]
@kyessenov @louiscryan @PiotrSikora would like to won't fix this in favor of forthcoming LDS API. Do we need independent support for this? cc @htuch

**Comment by mattklein123** [comment]
I'm closing this for now in favor of LDS and OOB conversations. We can reopen if this is needed.

**Comment by ctaggart** [comment]
I'm still not sure how to automatically reload certificates, so I posted the question to:
https://stackoverflow.com/q/54031488/23059
