### ISSUE TITLE
Namespace Envoy code

### ISSUE THREAD

**Issue by tschroed** [lyft/envoy#920]
Envoy code currently occupies the global namespace which can cause collisions when integrating with third party code. Moving all of Envoy into a top-level namespace with reasonably low probability of collision (e.g. lyft) would fix that.

**Comment by mattklein123** [comment]
@tschroed is this theoretical? Or it's causing you a real issue? Just trying to figure out how urgent it is to fix this. Will need to automate and make it part of check/fix format flow.

**Comment by tschroed** [comment]
Sadly, actual. Some collisions that I've run into already: proto = google::protobuf (can be fixed by changing a new short namespace name) and Thread.

I expect that we'd take on the work to update the code. Check/fix is an interesting consideration that hadn't occurred to me.

**Comment by mattklein123** [comment]
OK one interim option is to just fix the real collisions you have now while figuring out a better long term option. The two you mentioned should be simple.
