### ISSUE TITLE
Documentation: overlapping route prefixes

### ISSUE THREAD

**Issue by bryanlarsen** [lyft/envoy#938]
re: https://lyft.github.io/envoy/docs/configuration/http_conn_man/route_config/route.html

Please document the algorithm that is used when route prefixes overlap.

For example, if I route /api to apisvc and / to appsvc, how do I ensure that no /api requests are sent to appsvc?

@kflynn on gitter suggests that the algorithm is first match.    This may be surprising to users who are used to other algorithm's, like nginx's longest match, so it should be documented.   Thanks!

**Comment by mattklein123** [comment]
This is documented here: https://lyft.github.io/envoy/docs/configuration/http_conn_man/route_config/route_matching.html 

PRs appreciated if you would like to add any cross linking from elsewhere.
