### ISSUE TITLE
Remote UDP statsd support

### ISSUE THREAD

**Issue by jylin** [lyft/envoy#948]
Envoy seems to currently only support TCP statsd server with the property "statsd_tcp_cluster_name". The default server for statsd is the UDP one (https://github.com/etsy/statsd/blob/master/docs/server.md). It would be nice to support flushing stats to the statsd UDP server.

**Comment by mattklein123** [comment]
Already supported, see statsd_local_udp_port here: https://lyft.github.io/envoy/docs/configuration/overview/overview.html

**Comment by jylin** [comment]
Doesn't that option require that statsd or a listener be running on the same machine as Envoy? I was more interested in having a remote statsd server that is listening on UDP.

**Comment by mattklein123** [comment]
Yeah, not supported now. Reopening and clarifying request.
