### ISSUE TITLE
Segfault with extra / on admin address

### ISSUE THREAD

**Issue by kflynn** [lyft/envoy#952]
If you have 

```
  "admin": {
    "access_log_path": "/dev/null",
    "address": "tcp://127.0.0.1:8001/"
  }
```

(note the trailing `/` on the `address`) then Envoy will segfault. Deleting the trailing `/` cures the segfault.

Segfault is arguably a bit harsh as a misconfiguration diagnostic. ;)

**Comment by hennna** [comment]
The reason this is probably happening is because of my change to Network::Utility::resolveUrl that returns a nullptr when the address cannot be parsed. An easy fix would be to throw an exception instead. Do you want me take this or is there already a patch?

**Comment by mattklein123** [comment]
@hennna @ccaraman is working on a fix to refactor stuff to use exceptions. Feel free to sync up with each other offline.

**Comment by hennna** [comment]
Okay. @ccaraman feel free to ping me on any related changes.
