### ISSUE TITLE
Generalize concrete implementation registration and lookup.

### ISSUE THREAD

**Issue by tschroed** [lyft/envoy#967]
Tracing, stats, and logging should have dynamic registration for runtime lookup of specific implementations.

For example, right now there is a lightstep and a zipkin tracing implementation. These are selected using config values and if/else in MainImpl::initializeTracers.

Sometimes it's undesirable to even attempt to link against specific implementations. For example, Lightstep introduces a symbol collision with existing google3 code which we want to link in.

Instead we should have a dynamic registration mechanism similar to RegisterNetworkFilterConfigFactory that allows us to selectively link in dependencies.

**Comment by htuch** [comment]
Do we want to call this static registration to distinguish from fully dynamic registration (e.g. using ELF loadable objects?).

**Comment by tschroed** [comment]
I'm name agnostic. We could even just call it "registration".

**Comment by mattklein123** [comment]
+1 to this, and also doing the bazel work to make it easy to compile things in and out. The static registration can be modeled after the existing filter stuff.

**Comment by htuch** [comment]
Should we use reverse DNS naming notation? Also see https://github.com/lyft/envoy-api/issues/34.

**Comment by tschroed** [comment]
Works for me.

Slightly more crazy: we could have a single registry for all of this stuff to make it readily extensible to new classes of things. However, retrieval probably ends up involving a static_cast which makes me a bit uncomfortable.

**Comment by mattklein123** [comment]
I think you mean ```dynamic_cast```, but the single registry is an interesting idea and might remove duplication. Don't feel strongly either way.

**Comment by mattklein123** [comment]
@tschroed I'm going to close this as done. I think we have general agreement on approach here. We can add new registration for things like stats as needed.
