### ISSUE TITLE
Add local address IP version as CLI option

### ISSUE THREAD

**Issue by hennna** [lyft/envoy#979]
Thoughts on whether this can be used for both:

1. Initializing LocalInfo (https://github.com/lyft/envoy/blob/master/source/exe/main.cc#L67) and 
2. UdpStatsdSink local address
https://github.com/lyft/envoy/blob/master/source/common/stats/statsd.cc#L23

Or should the UdpStatsdSink local address version be a separate json field?

**Comment by mattklein123** [comment]
For (1), I agree we should add a CLI option that can optionally populate LocalInfo.

For (2), this is related to https://github.com/lyft/envoy/issues/948. This is not going to make the 1.3.0 config freeze, but we could deprecate the local UDP port field and add a local UDP address field instead which would fix both your issue as well as the other issue.
