### ISSUE TITLE
Gracefully handle EMFILE (too many open files) errors.

### ISSUE THREAD

**Issue by PiotrSikora** [lyft/envoy#980]
Running out of file descriptors when accepting new connections is perfectly fine and acts as circuit breaker, so Envoy shouldn't be crashing when it cannot accept new connections.

**Comment by mattklein123** [comment]
From an operational perspective, I'm fundamentally opposed to this behavior. I've been burned by this too many times. When a process runs out of FDs and attempts to gracefully handle, bizarre things can happen including not being able to write logs, not being able to emit stats, etc. The fact that Envoy treats a lack of FDs as an OOM condition and crashes is very much on purpose. 

On a properly configured system, there is no reason to ever run out of FDs.

With all of that said, if people want this behavior, we can do it, but it must be configurable and have full test coverage.

**Comment by dnoe** [comment]
We have an internal bug ticket assigned to me for designing a mechanism that does connection resource tracking including memory and FD usage and gracefully terminates some of the most idle connections when we start to get under resource pressure with the goal of preventing this scenario.  I think properly implementing this is a better solution than trying to handle EMFILE when it occurs.  I don't remember if there is a corresponding GH issue yet but if not I will create it.

**Comment by mattklein123** [comment]
@dnoe agreed. Here is your GH: https://github.com/lyft/envoy/issues/373 :)

Please put design notes there.

**Comment by mattklein123** [comment]
@PiotrSikora I would like to close this in favor of #373. Or do you prefer to keep this open and make the behavior configurable?

**Comment by mattklein123** [comment]
Closing in favor of #373. We can reopen if there is widespread disagreement on this. cc @dnoe
