### ISSUE TITLE
Comparison to linkerd

### ISSUE THREAD

**Issue by jparise** [lyft/envoy#99]
The documentation's [comparison list](https://lyft.github.io/envoy/docs/intro/comparison.html) is both thorough and useful. Thanks for that!

Would you consider adding a brief comparison to [linkerd](https://linkerd.io/)? It's based on Finagle, so I would expect the existing section to cover most of the details, but as a proxy product, linkerd is even more similar to Envoy (and a competitor).

**Comment by mattklein123** [comment]
Sure, we can add a comparison.

@olix0r let me know if you or someone from Bouyant wants to write the comparison. You can email me offline to discuss if you want. Otherwise I will write it.

**Comment by olix0r** [comment]
Thanks for looping me in, @mattklein123. I'll talk to the team this morning and find a volunteer.

**Comment by olix0r** [comment]
Here's what we came up with:

> linkerd is a standalone, open source RPC routing proxy built on Netty and Finagle. linkerd offers many of Finagle’s features, including latency-aware load balancing, connection pooling, circuit-breaking, retry budgets, deadlines, tracing, fine-grained instrumentation, and a traffic routing layer for request-level routing. linkerd provides a pluggable service discovery interface (with standard support for Consul and ZooKeeper, as well as the Marathon and Kubernetes APIs).
>
> linkerd’s memory and CPU requirements are significantly higher than Envoy’s. However, its underlying tech is extensively production tested and widely deployed. In contrast to Envoy, linkerd provides a minimalist configuration language, and explicitly does not support hot reloads, relying instead on dynamic provisioning and service abstractions. linkerd supports HTTP/1.1, Thrift, ThriftMux, HTTP/2 (experimental) and gRPC (experimental).

If there's anything else you think should be addressed, just let us know!

**Comment by mattklein123** [comment]
Sure that sounds fine. I will do a PR to get it in.

**Comment by mattklein123** [comment]
https://github.com/lyft/envoy/pull/145

**Comment by jamiely** [comment]
The comparison is now at https://lyft.github.io/envoy/docs/intro/comparison.html for those coming from search engines.

**Comment by rafaelcaricio** [comment]
All comparison pages are gone now. Where can we get a link to a comparison?

**Comment by moderation** [comment]
Maintaining accurate comparisons is time consuming. There are a number of third party sites that provide this information like https://layer5.io/landscape
