### ISSUE TITLE
Make ratelimit timeout configurable

### ISSUE THREAD

**Issue by rossabaker** [lyft/envoy#990]
Ratelimit calls have a [hardcoded timeout of 20 milliseconds](https://github.com/lyft/envoy/blob/23d1acd7ec5836bc1a754047ca18d0ec4998eeda/source/server/config/http/ratelimit.cc#L25).  When latency is too high, the ratelimit service gets called, but envoy receives a 504 and allows the request proceed.  This timeout should be configurable.

**Comment by htuch** [comment]
This is flaking `//test/integration:ratelimit_integration_test`, so I'll look into fixing this.
